import { analytics } from './posthog';

export const TestagramEvent = {
  SIGNED_UP: 'testagram_signed_up',
  LOGGED_IN: 'testagram_logged_in',
  LOGGED_OUT: 'testagram_logged_out',
  PROFILE_VIEWED: 'profile_viewed',
  PROFILE_UPDATED: 'profile_updated',
  POST_CREATED: 'post_created',
  POST_VIEWED: 'post_viewed',
  POST_LIKED: 'post_liked',
  POST_UNLIKED: 'post_unliked',
  POST_SHARED: 'post_shared',
  POST_REPOSTED: 'post_reposted',
  POST_UNREPOSTED: 'post_unreposted',
  POST_DELETED: 'post_deleted',
  USER_FOLLOWED: 'user_followed',
  USER_UNFOLLOWED: 'user_unfollowed',
  SEARCH_PERFORMED: 'search_performed',
  SEARCH_RESULT_OPENED: 'search_result_opened',
  MESSAGE_SENT: 'message_sent',
  MESSAGE_EDITED: 'message_edited',
  MESSAGE_DELETED: 'message_deleted',
  MESSAGE_REACTED: 'message_reacted',
  CALL_STARTED: 'testagram_call_started',
  CALL_JOINED: 'testagram_call_joined',
  CALL_ENDED: 'testagram_call_ended',
  NOTIFICATION_OPENED: 'notification_opened',
  NOTIFICATION_READ: 'notification_read',
  BOOKMARK_ADDED: 'bookmark_added',
  BOOKMARK_REMOVED: 'bookmark_removed',
  COMMUNITY_CREATED: 'community_created',
  COMMUNITY_JOINED: 'community_joined',
  COMMUNITY_LEFT: 'community_left',
  AD_CREATE_VIEWED: 'ad_create_viewed',
  AD_CREATED: 'testagram_ad_created',
  AD_PAYMENT_INITIATED: 'testagram_ad_payment_initiated',
  AD_PAYMENT_CONFIRMED: 'testagram_ad_payment_confirmed',
  AD_PAYMENT_FAILED: 'testagram_ad_payment_failed',
  AD_ACTIVATED: 'testagram_ad_activated',
  AD_VIEWED: 'testagram_ad_viewed',
  AD_CLICKED: 'testagram_ad_clicked',
  CAMPAIGN_CREATED: 'campaign_created',
  CAMPAIGN_PUBLISHED: 'campaign_published',
  CAMPAIGN_ACTIVATED: 'campaign_activated',
  WALLET_DEPOSIT_STARTED: 'wallet_deposit_started',
  WALLET_DEPOSIT_COMPLETED: 'wallet_deposit_completed',
  WALLET_TRANSACTION_FAILED: 'wallet_transaction_failed',
  WALLET_TRANSACTION_VIEWED: 'wallet_transaction_viewed',
  MEDIA_UPLOAD_STARTED: 'media_upload_started',
  MEDIA_UPLOAD_COMPLETED: 'media_upload_completed',
  MEDIA_UPLOAD_FAILED: 'media_upload_failed',
  CAPABILITY_SUCCEEDED: 'testagram_capability_succeeded',
  CAPABILITY_FAILED: 'testagram_capability_failed',
  SESSION_STARTED: 'testagram_session_started',
} as const;

export type TestagramEventName = (typeof TestagramEvent)[keyof typeof TestagramEvent];

export function trackTestagramEvent(event: TestagramEventName, properties?: Record<string, unknown>): void {
  analytics.track(event, { app: 'testagram', ...properties });
}
