export type TestagramEmojiOptions = { base?: string; folder?: string; ext?: string; className?: string; size?: number | string; title?: boolean };
const DEFAULTS = { base: "https://cdn.jsdelivr.net/gh/jdecked/twemoji@17.0.3/assets/", folder: "svg", ext: ".svg", className: "testagram-emoji", size: "svg", title: false } as const;
const variation = (n: number) => n === 0xfe0f || n === 0xfe0e;
const modifier = (n: number) => n >= 0x1f3fb && n <= 0x1f3ff;
const joiner = (n: number) => n === 0x200d;
const id = (s: string) => Array.from(s).map(c => c.codePointAt(0)!.toString(16)).filter((_, i, a) => i === 0 || !variation(parseInt(a[i], 16))).join("-");
function sequenceAt(text: string, start: number): string | null { const chars = Array.from(text.slice(start)); if (!chars.length) return null; const first = chars[0].codePointAt(0)!; if (first < 0x1f000 && ![0xa9,0xae,0x203c,0x2049,0x2122].includes(first)) return null; let out=chars[0], i=1; while(i<chars.length){const cp=chars[i].codePointAt(0)!; if(variation(cp)||modifier(cp)) out+=chars[i++]; else if(joiner(cp)&&chars[i+1]) out+=chars[i++]+chars[i++]; else break;} return out; }
export function parseTwemoji(root: HTMLElement, options: TestagramEmojiOptions = {}): void { if(typeof document === "undefined") return; const c={...DEFAULTS,...options}; const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT); const nodes: Text[]=[]; let n=w.nextNode(); while(n){if(n.parentElement&&!n.parentElement.closest("script,style,textarea,[data-no-emoji]"))nodes.push(n as Text); n=w.nextNode();} for(const node of nodes){const text=node.nodeValue??"", f=document.createDocumentFragment(); let cursor=0, changed=false; const chars=Array.from(text); for(let i=0;i<chars.length;i++){const off=chars.slice(0,i).join("").length; const seq=sequenceAt(text,off); if(!seq)continue; const before=text.slice(cursor,off); if(before)f.appendChild(document.createTextNode(before)); const img=document.createElement("img"); img.className=c.className; img.alt=seq; img.draggable=false; img.loading="lazy"; img.decoding="async"; img.setAttribute("role","img"); if(c.title)img.title=seq; img.src=`${c.base.replace(/\/$/,"")}/${c.folder}/${id(seq)}${c.ext}`; f.appendChild(img); cursor=off+seq.length; i+=Array.from(seq).length-1; changed=true;} if(changed){if(cursor<text.length)f.appendChild(document.createTextNode(text.slice(cursor))); node.parentNode?.replaceChild(f,node);}} }
export function emojiAssetUrl(emoji: string, options: TestagramEmojiOptions = {}): string { const c={...DEFAULTS,...options}; return `${c.base.replace(/\/$/,"")}/${c.folder}/${id(emoji)}${c.ext}`; }
