listen 1935;
max_connections 10000;
daemon off;
srs_log_tank console;

http_api {
  enabled on;
  listen 1985;
}

rtc_server {
  enabled on;
  listen 8000;
  candidate $CANDIDATE;
  tcp {
    enabled on;
    listen 8000;
  }
  protocol all;
}

vhost __defaultVhost__ {
  rtc {
    enabled on;
    rtc_to_rtmp on;
    rtmp_to_rtc off;
    nack on;
    twcc on;
  }

  http_hooks {
    enabled on;
    on_publish https://www.testagram.site/api/live?srs=auth;
    on_unpublish https://www.testagram.site/api/live?srs=auth;
  }

  forward {
    enabled on;
    backend https://www.testagram.site/api/live?srs=forward;
  }
}
