import { supabase } from '@/lib/supabase';
import { backendCapabilities, type CapabilityPage } from '@/services/testagramCapabilityClient';
import { communicationCrypto } from '@/services/communicationCrypto';
import { TestagramEvent, trackTestagramEvent } from '@/lib/testagram-analytics';

export type CommunicationConversation = { id: string; created_at: string; updated_at: string; latest_message?: Record<string, unknown> | null; [key: string]: unknown };
export type CommunicationMessage = { id: string; conversation_id: string; sender_id: string; body: string; media_url?: string | null; media_type?: string | null; created_at: string; edited_at?: string | null; deleted_at?: string | null; reply_to_message_id?: string | null; shared_post_id?: string | null; client_message_id?: string | null; delivered_at?: string | null; read_at?: string | null; e2ee_enabled?: boolean; e2ee_version?: string | null; e2ee_epoch?: number | null; ciphertext?: string | null; nonce?: string | null; aad?: string | null; sender?: Record<string, unknown> | null };
export type MessageAttachment = { id: string; message_id: string; owner_id: string; media_url: string; media_type: string; mime_type?: string | null; byte_size: number; duration_ms?: number | null; width?: number | null; height?: number | null; created_at: string };
export type TypingState = { user_id: string; typing: boolean; at: string };
export type PresenceState = { user_id: string; status: 'online' | 'away' | 'offline'; at: string };
export type CallSession = { call_id: string; provider: 'testagram-native' | 'testagram-p2p'; room_name: string; conversation_id?: string; created_by?: string; status?: 'ringing' | 'active' | 'ended' | 'failed'; kind?: 'voice' | 'video' | 'screen'; e2ee_enabled?: boolean; e2ee_epoch?: number | null };
export type CallSessionChange = { operation: 'INSERT' | 'UPDATE' | 'DELETE'; session: CallSession; previous?: Partial<CallSession> | null };
export type ConversationSettings = { conversation_id: string; user_id: string; archived_at?: string | null; pinned_at?: string | null; muted_until?: string | null; disappearing_seconds?: number | null };
export type CommunicationStatus = { id: string; user_id: string; media_url?: string | null; media_type: 'text' | 'image' | 'video'; caption?: string | null; background?: string | null; created_at: string; expires_at: string };

const conversationTopic = (conversationId: string) => `conversation:${conversationId}`;
type ConversationHandlers = { onMessage?: (message: CommunicationMessage) => void; onMessageChanged?: (message: CommunicationMessage) => void; onMessageDeleted?: (message: CommunicationMessage) => void; onTyping?: (state: TypingState) => void; onPresence?: (state: PresenceState) => void; onCall?: (change: CallSessionChange) => void };
type CallHandlers = { onCall?: (change: CallSessionChange) => void };
const normalizeCall = (row: Record<string, unknown>): CallSession => { const metadata = (row.metadata && typeof row.metadata === 'object' ? row.metadata : {}) as Record<string, unknown>; return { ...(row as CallSession), call_id: String(row.id ?? row.call_id), provider: 'testagram-native', e2ee_enabled: Boolean(metadata.e2ee_enabled ?? row.e2ee_enabled), e2ee_epoch: metadata.e2ee_epoch == null && row.e2ee_epoch == null ? null : Number(metadata.e2ee_epoch ?? row.e2ee_epoch), }; };
const encryptInput = async (conversationId: string, body: string) => { const encrypted = await communicationCrypto.encryptMessage(conversationId, body); return { ...encrypted, aad: `${conversationId}:${encrypted.epoch}`, e2ee_version: 'v1' }; };

export const communicationService = {
  listConversations(limit = 50) { return backendCapabilities.call<{ items: CommunicationConversation[] }>('testagram.conversations.list', { limit }); },
  createConversation(memberIds: string[]) { return backendCapabilities.call<{ conversation_id: string }>('testagram.conversations.create', { member_ids: memberIds }); },
  async listMessages(conversationId: string, limit = 50, cursor?: string) { const result = await backendCapabilities.call<CapabilityPage<CommunicationMessage>>('testagram.messages.list', { conversation_id: conversationId, limit, ...(cursor ? { cursor } : {}) }); return { ...result, items: await this.decryptMessages(result.items ?? []) }; },
  async decryptMessage(message: CommunicationMessage) { const attachment = Array.isArray((message as any).attachment_metadata) ? (message as any).attachment_metadata[0] : null; const normalized = { ...message, e2ee_enabled: message.e2ee_enabled ?? Boolean(message.ciphertext && message.nonce), e2ee_epoch: message.e2ee_epoch ?? (message as any).key_epoch ?? null, reply_to_message_id: message.reply_to_message_id ?? (message as any).reply_to_id ?? null, media_url: message.media_url ?? attachment?.media_url ?? null, media_type: message.media_type ?? attachment?.media_type ?? null }; if (!normalized.e2ee_enabled || !normalized.ciphertext || !normalized.nonce || normalized.e2ee_epoch == null) return normalized; const body = await communicationCrypto.decryptMessage(normalized.conversation_id, normalized.e2ee_epoch, normalized.ciphertext, normalized.nonce, normalized.aad ?? undefined); return { ...normalized, body }; },
  async decryptMessages(messages: CommunicationMessage[]) { return Promise.all(messages.map(message => this.decryptMessage(message))); },
  async sendMessage(input: { conversationId: string; body: string; clientMessageId?: string; replyToMessageId?: string; sharedPostId?: string }) {
    const encrypted = await encryptInput(input.conversationId, input.body);
    const result = await backendCapabilities.call<{ message_id: string; encrypted: boolean }>('testagram.messages.send_encrypted', { conversation_id: input.conversationId, e2ee_epoch: encrypted.epoch, ciphertext: encrypted.ciphertext, nonce: encrypted.nonce, ...(input.clientMessageId ? { client_message_id: input.clientMessageId } : {}), ...(input.replyToMessageId ? { reply_to_message_id: input.replyToMessageId } : {}), ...(input.sharedPostId ? { shared_post_id: input.sharedPostId } : {}) });
    trackTestagramEvent(TestagramEvent.MESSAGE_SENT, { conversation_id: input.conversationId, message_id: result.message_id, has_reply: Boolean(input.replyToMessageId), has_shared_post: Boolean(input.sharedPostId), encrypted: true }); return result;
  },
  async editMessage(messageId: string, body: string, conversationId: string) { const encrypted = await encryptInput(conversationId, body); const result = await backendCapabilities.call<{ message_id: string; edited: boolean }>('testagram.messages.edit_encrypted', { message_id: messageId, e2ee_epoch: encrypted.epoch, ciphertext: encrypted.ciphertext, nonce: encrypted.nonce }); trackTestagramEvent(TestagramEvent.MESSAGE_EDITED, { message_id: result.message_id, encrypted: true }); return result; },
  async deleteMessage(messageId: string) { const result = await backendCapabilities.call<{ message_id: string; deleted: boolean }>('testagram.messages.delete', { message_id: messageId }); trackTestagramEvent(TestagramEvent.MESSAGE_DELETED, { message_id: result.message_id }); return result; },
  attachMessage(input: { messageId: string; mediaUrl: string; mediaType: string; mimeType?: string; byteSize: number; durationMs?: number; width?: number; height?: number }) { return backendCapabilities.call<{ attachment: MessageAttachment }>('testagram.messages.attach', { message_id: input.messageId, attachment_metadata: { media_url: input.mediaUrl, media_type: input.mediaType, ...(input.mimeType ? { mime_type: input.mimeType } : {}), byte_size: input.byteSize, ...(input.durationMs !== undefined ? { duration_ms: input.durationMs } : {}), ...(input.width !== undefined ? { width: input.width } : {}), ...(input.height !== undefined ? { height: input.height } : {}) } }); },
  markMessageRead(messageId: string) { return backendCapabilities.call<{ message_id: string; read: boolean }>('testagram.messages.mark_read', { message_id: messageId }); },
  async reactToMessage(messageId: string, reaction: string, remove = false) { const result = await backendCapabilities.call<{ message_id: string; reaction: string; removed: boolean }>('testagram.messages.react', { message_id: messageId, reaction, remove }); trackTestagramEvent(TestagramEvent.MESSAGE_REACTED, { message_id: messageId, reaction, removed: result.removed }); return result; },
  async starMessage(messageId: string) { const { data: session } = await supabase.auth.getSession(); if (!session.session?.user.id) throw new Error('Authentication required'); const { error } = await supabase.from('message_stars').upsert({ message_id: messageId, user_id: session.session.user.id }, { onConflict: 'message_id,user_id' }); if (error) throw error; return true; },
  async unstarMessage(messageId: string) { const { data: session } = await supabase.auth.getSession(); if (!session.session?.user.id) throw new Error('Authentication required'); const { error } = await supabase.from('message_stars').delete().eq('message_id', messageId).eq('user_id', session.session.user.id); if (error) throw error; return true; },
  async listStarredMessages(limit = 100) { const { data, error } = await supabase.from('message_stars').select('message_id,created_at,messages(*)').order('created_at', { ascending: false }).limit(limit); if (error) throw error; return data ?? []; },
  async getConversationSettings(conversationId: string) { const { data: session } = await supabase.auth.getSession(); if (!session.session?.user.id) throw new Error('Authentication required'); const { data, error } = await supabase.from('conversation_settings').select('*').eq('conversation_id', conversationId).eq('user_id', session.session.user.id).maybeSingle(); if (error) throw error; return data as ConversationSettings | null; },
  async setConversationSettings(conversationId: string, patch: Partial<Omit<ConversationSettings, 'conversation_id' | 'user_id'>>) { const { data: session } = await supabase.auth.getSession(); if (!session.session?.user.id) throw new Error('Authentication required'); const { data, error } = await supabase.from('conversation_settings').upsert({ conversation_id: conversationId, user_id: session.session.user.id, ...patch, updated_at: new Date().toISOString() }, { onConflict: 'conversation_id,user_id' }).select('*').single(); if (error) throw error; return data as ConversationSettings; },
  async listStatuses(limit = 100) { const { data, error } = await supabase.from('communication_statuses').select('*').gt('expires_at', new Date().toISOString()).order('created_at', { ascending: false }).limit(limit); if (error) throw error; return (data ?? []) as CommunicationStatus[]; },
  async createTextStatus(text: string, background = 'default') { const { data: session } = await supabase.auth.getSession(); const userId = session.session?.user.id; if (!userId) throw new Error('Authentication required'); const { data, error } = await supabase.from('communication_statuses').insert({ user_id: userId, media_type: 'text', caption: text, background }).select('*').single(); if (error) throw error; return data as CommunicationStatus; },
  async createMediaStatus(mediaUrl: string, mediaType: 'image' | 'video', caption = '') { const { data: session } = await supabase.auth.getSession(); const userId = session.session?.user.id; if (!userId) throw new Error('Authentication required'); const { data, error } = await supabase.from('communication_statuses').insert({ user_id: userId, media_url: mediaUrl, media_type: mediaType, caption }).select('*').single(); if (error) throw error; return data as CommunicationStatus; },
  async markStatusViewed(statusId: string) { const { data: session } = await supabase.auth.getSession(); const userId = session.session?.user.id; if (!userId) throw new Error('Authentication required'); const { error } = await supabase.from('communication_status_views').upsert({ status_id: statusId, viewer_id: userId }, { onConflict: 'status_id,viewer_id' }); if (error) throw error; return true; },
  async createCall(conversationId: string, kind: 'voice' | 'video' | 'screen' = 'video') { const result = await backendCapabilities.call<CallSession>('testagram.calls.create', { conversation_id: conversationId, kind, e2ee_enabled: true }); trackTestagramEvent('testagram_call_started' as never, { conversation_id: conversationId, call_id: result.call_id, kind, encrypted: true, e2ee_mode: 'dtls-srtp-p2p', transport: 'testagram-p2p' }); return result; },
  async joinCall(callId: string) { const result = await backendCapabilities.call<{ call_id: string; joined: boolean; conversation_id?: string }>('testagram.calls.join', { call_id: callId }); trackTestagramEvent('testagram_call_joined' as never, { call_id: result.call_id }); return result; },
  async endCall(callId: string) { const result = await backendCapabilities.call<{ call_id: string; ended: boolean }>('testagram.calls.end', { call_id: callId }); trackTestagramEvent('testagram_call_ended' as never, { call_id: result.call_id }); return result; },
  subscribeToConversation(conversationId: string, handlers: ConversationHandlers = {}) {
    const channel = supabase.channel(conversationTopic(conversationId), { config: { private: true, broadcast: { self: false } } })
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages', filter: `conversation_id=eq.${conversationId}` }, payload => { void this.decryptMessage(payload.new as CommunicationMessage).then(message => handlers.onMessage?.(message)); })
      .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'messages', filter: `conversation_id=eq.${conversationId}` }, payload => { void this.decryptMessage(payload.new as CommunicationMessage).then(message => handlers.onMessageChanged?.(message)); })
      .on('postgres_changes', { event: 'DELETE', schema: 'public', table: 'messages', filter: `conversation_id=eq.${conversationId}` }, payload => { void this.decryptMessage(payload.old as CommunicationMessage).then(message => handlers.onMessageDeleted?.(message)); })
      .on('broadcast', { event: 'typing' }, payload => { if (payload.payload) handlers.onTyping?.(payload.payload as TypingState); })
      .on('presence', { event: 'sync' }, () => {
        const state = channel.presenceState();
        Object.values(state).flat().forEach(entry => handlers.onPresence?.(entry as unknown as PresenceState));
      })
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'calls', filter: `conversation_id=eq.${conversationId}` }, payload => handlers.onCall?.({ operation: 'INSERT', session: normalizeCall(payload.new as Record<string, unknown>) }))
      .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'calls', filter: `conversation_id=eq.${conversationId}` }, payload => handlers.onCall?.({ operation: 'UPDATE', session: normalizeCall(payload.new as Record<string, unknown>), previous: payload.old as Partial<CallSession> }))
      .on('postgres_changes', { event: 'DELETE', schema: 'public', table: 'calls', filter: `conversation_id=eq.${conversationId}` }, payload => handlers.onCall?.({ operation: 'DELETE', session: normalizeCall(payload.old as Record<string, unknown>) }))
      .subscribe((status, error) => { if (error) console.warn('[communication] conversation realtime error', status, error); });
    return () => { void supabase.removeChannel(channel); };
  },

  subscribeToCallSessions(conversationId: string, handlersOrCallback: CallHandlers | ((change: CallSessionChange) => void) = {}) { const handlers: CallHandlers = typeof handlersOrCallback === 'function' ? { onCall: handlersOrCallback } : handlersOrCallback; const channel = supabase.channel(conversationTopic(conversationId), { config: { private: true, broadcast: { self: false } } }).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'calls', filter: `conversation_id=eq.${conversationId}` }, payload => handlers.onCall?.({ operation: 'INSERT', session: normalizeCall(payload.new as Record<string, unknown>) })).on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'calls', filter: `conversation_id=eq.${conversationId}` }, payload => handlers.onCall?.({ operation: 'UPDATE', session: normalizeCall(payload.new as Record<string, unknown>), previous: payload.old as Partial<CallSession> })).on('postgres_changes', { event: 'DELETE', schema: 'public', table: 'calls', filter: `conversation_id=eq.${conversationId}` }, payload => handlers.onCall?.({ operation: 'DELETE', session: normalizeCall(payload.old as Record<string, unknown>) })).subscribe((status, error) => { if (error) console.warn('[communication] call realtime error', status, error); }); return () => { void supabase.removeChannel(channel); }; },
  async setTyping(conversationId: string, typing: boolean) { const channel = supabase.channel(conversationTopic(conversationId), { config: { private: true, broadcast: { self: false, ack: true } } }); const session = await supabase.auth.getSession(); const userId = session.data.session?.user.id; if (!userId) throw new Error('Authentication required'); await channel.subscribe(); try { const result = await channel.send({ type: 'broadcast', event: 'typing', payload: { user_id: userId, typing, at: new Date().toISOString() } }); if (result !== 'ok') throw new Error(`Typing broadcast failed: ${String(result)}`); } finally { await supabase.removeChannel(channel); } },
  async setPresence(conversationId: string, status: PresenceState['status']) { const channel = supabase.channel(conversationTopic(conversationId), { config: { private: true } }); const session = await supabase.auth.getSession(); const userId = session.data.session?.user.id; if (!userId) throw new Error('Authentication required'); await channel.subscribe(); try { const result = await channel.track({ user_id: userId, status, at: new Date().toISOString() }); if (result !== 'ok') throw new Error(`Presence update failed: ${String(result)}`); } finally { await supabase.removeChannel(channel); } },
};
