import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const URL=Deno.env.get('SUPABASE_URL')??'';
const ANON=Deno.env.get('SUPABASE_ANON_KEY')??Deno.env.get('SUPABASE_PUBLISHABLE_KEY')??'';
const HS=(Deno.env.get('MATRIX_HOMESERVER')??'').replace(/\/$/,'');
const TOKEN=Deno.env.get('MATRIX_SERVICE_ACCESS_TOKEN')??'';
const BOT=Deno.env.get('MATRIX_BOT_USER_ID')??'';
const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers});
function configured(){return Boolean(HS&&TOKEN&&BOT)}
async function matrix(path:string,init:RequestInit={}){if(!configured())throw Error('Matrix bridge is not configured');const h=new Headers(init.headers);h.set('Authorization',`Bearer ${TOKEN}`);h.set('Content-Type','application/json');const r=await fetch(`${HS}/_matrix/client/v3${path}`,{...init,headers:h});const t=await r.text();let b:unknown;try{b=JSON.parse(t)}catch{b=t.slice(0,2000)}if(!r.ok)throw Error(`Matrix ${r.status}: ${typeof b==='string'?b:JSON.stringify(b)}`);return b}
async function user(req:Request){const a=req.headers.get('Authorization');if(!a?.startsWith('Bearer '))throw Error('Bearer authentication required');const c=createClient(URL,ANON,{global:{headers:{Authorization:a}},auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await c.auth.getUser();if(error||!data.user)throw Error('Authenticated Testagram user required');return {client:c,user:data.user}}
async function isMember(c:ReturnType<typeof createClient>,uid:string,cid:string){const {data,error}=await c.from('conversation_members').select('user_id').eq('conversation_id',cid).eq('user_id',uid).maybeSingle();if(error)throw Error(error.message);return Boolean(data)}
Deno.serve(async req=>{if(req.method==='OPTIONS')return json({},204);if(req.method!=='POST')return json({ok:false,error:'POST required'},405);try{const {client,user:authedUser}=await user(req);const b=await req.json().catch(()=>({}));const op=String(b.operation??'health');if(op==='health')return json({ok:true,service:'matrix-bridge',configured:configured(),homeserver:HS||null});if(op==='link_identity'){const {data,error}=await client.rpc('upsert_matrix_identity',{p_matrix_user_id:String(b.matrix_user_id??''),p_homeserver:String(b.homeserver??HS)});if(error)throw Error(error.message);return json({ok:true,identity:data})}if(op==='create_room'){const cid=String(b.conversation_id??'');if(!cid||!(await isMember(client,authedUser.id,cid)))return json({ok:false,error:'Conversation membership required'},403);const old=await client.from('matrix_conversation_rooms').select('*').eq('conversation_id',cid).maybeSingle();if(old.error)throw Error(old.error.message);if(old.data)return json({ok:true,room:old.data,idempotent:true});const r=await matrix('/createRoom',{method:'POST',body:JSON.stringify({name:`Testagram ${cid}`,preset:'private_chat',is_direct:true,invite:[]})}) as {room_id?:string};if(!r.room_id)throw Error('Matrix did not return room_id');const {data,error}=await client.from('matrix_conversation_rooms').insert({conversation_id:cid,room_id:r.room_id,homeserver:HS,status:'active'}).select('*').single();if(error)throw Error(error.message);return json({ok:true,room:data},201)}if(op==='send_event'){const cid=String(b.conversation_id??''),type=String(b.event_type??'m.room.message'),content=b.content&&typeof b.content==='object'?b.content:null;if(!cid||!content||!(await isMember(client,authedUser.id,cid)))return json({ok:false,error:'Conversation membership required'},403);const m=await client.from('matrix_conversation_rooms').select('room_id,status').eq('conversation_id',cid).maybeSingle();if(m.error)throw Error(m.error.message);if(!m.data||m.data.status!=='active')return json({ok:false,error:'Matrix room is not active for this conversation'},409);const result=await matrix(`/rooms/${encodeURIComponent(m.data.room_id)}/send/${encodeURIComponent(type)}/testagram-${crypto.randomUUID()}`,{method:'PUT',body:JSON.stringify(content)});return json({ok:true,room_id:m.data.room_id,event:result})}return json({ok:false,error:'Unknown Matrix bridge operation'},400)}catch(e){console.error('matrix-bridge',e);return json({ok:false,error:e instanceof Error?e.message:'Matrix bridge failed'},502)}});
