import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders } from "npm:@supabase/supabase-js@2/cors";
const URL=Deno.env.get("SUPABASE_URL")??""; const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??Deno.env.get("SUPABASE_SECRET_KEY")??""; const SIGNING_SECRET=Deno.env.get("ZENAD_EVENT_SIGNING_SECRET")??SERVICE;
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}}); const cors={...corsHeaders,"Access-Control-Allow-Methods":"POST,OPTIONS"}; const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const EVENTS=new Set(["click","viewable","video_start","video_first_quartile","video_midpoint","video_third_quartile","video_complete"]);
function b64url(bytes:Uint8Array){let s="";for(const x of bytes)s+=String.fromCharCode(x);return btoa(s).replaceAll("+","-").replaceAll("/","_").replace(/=+$/g,"");}
function fromB64url(s:string){const p=s.replaceAll("-","+").replaceAll("_","/");const pad="=".repeat((4-p.length%4)%4);return Uint8Array.from(atob(p+pad),c=>c.charCodeAt(0));}
async function sign(value:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(SIGNING_SECRET),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64url(new Uint8Array(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value))));}
async function verifyToken(token:string,impressionId:string){const [payload,provided]=String(token).split(".");if(!payload||!provided)return false;const expected=await sign(payload);const a=fromB64url(provided),b=fromB64url(expected);if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];if(diff!==0)return false;const data=JSON.parse(new TextDecoder().decode(fromB64url(payload)));return data?.i===impressionId&&Number(data?.e)>Math.floor(Date.now()/1000);}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);if(!SERVICE||!SIGNING_SECRET)return json({error:'Ad event service is not configured'},503);try{const b=await req.json();const impressionId=String(b.impressionId??'');const eventType=String(b.eventType??'');const eventToken=String(b.eventToken??'');if(!impressionId||!EVENTS.has(eventType))return json({error:'Invalid event'},400);if(!eventToken||!(await verifyToken(eventToken,impressionId)))return json({error:'Invalid or expired event token'},401);const {data:imp}=await admin.from('testagram_ad_impressions').select('campaign_id,user_id,created_at').eq('impression_id',impressionId).maybeSingle();if(!imp)return json({error:'Unknown impression'},404);if(eventType==='click'){const {data:ok,error}=await admin.rpc('testagram_record_ad_click',{p_impression_id:impressionId});if(error)throw error;if(ok!==true)return json({ok:true,deduplicated:true});return json({ok:true});}const {error}=await admin.from('testagram_ad_events').insert({impression_id:impressionId,event_type:eventType,user_id:imp.user_id,metadata:b.metadata??{}});if(error?.code==='23505')return json({ok:true,deduplicated:true});if(error)throw error;return json({ok:true});}catch(e){console.error('zenad-event error',e);return json({error:'Event recording failed'},500);}});
