import "jsr:@supabase/functions-js/edge-runtime.d.ts";

// Public federation edge. It verifies the signature against the PUBLIC URL,
// then forwards only edge-verified activities to the hardened inbox processor.
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")||"";
const INBOX=`${SUPABASE_URL}/functions/v1/federation-inbox`;
const API=`${SUPABASE_URL}/functions/v1/mastodon-federation`;
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"accept,content-type,date,digest,signature,signature-input,content-digest,host","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const b64=(x:ArrayBuffer|Uint8Array)=>btoa(String.fromCharCode(...new Uint8Array(x)));
const ub64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const pem=(s:string)=>ub64(s.replace(/-----BEGIN PUBLIC KEY-----|-----END PUBLIC KEY-----|\s/g,""));
const uri=(v:unknown)=>typeof v==='string'?v:(v&&typeof v==='object'&&typeof (v as any).id==='string'?(v as any).id:'');
function sigParts(v:string){const o:any={};for(const p of v.split(/,(?=\w+=)/)){const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=p.slice(i+1).trim().replace(/^"|"$/g,'')}return o}
async function actorJson(actor:string){const r=await fetch(actor,{headers:{Accept:'application/activity+json, application/ld+json;q=0.9'}});if(!r.ok)throw Error(`actor fetch failed: ${r.status}`);return r.json()}
function validActor(a:any,uri:string){return a?.id===uri&&['Person','Service','Organization','Group','Application'].includes(a?.type)&&typeof a?.publicKey?.publicKeyPem==='string'}
async function verifyLegacy(req:Request,raw:string,actor:string){const s=req.headers.get('signature'),d=req.headers.get('digest'),date=req.headers.get('date');if(!s||!d||!date)throw Error('missing HTTP signature headers');if(Math.abs(Date.now()-Date.parse(date))>12*60*60*1000)throw Error('stale Date header');const expected=`SHA-256=${b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)))}`;if(d.toLowerCase()!==expected.toLowerCase())throw Error('digest mismatch');const p=sigParts(s);if((p.algorithm||'').toLowerCase()!=='rsa-sha256'||!p.signature||!p.keyId||!p.headers)throw Error('unsupported HTTP signature');if(p.keyId.split('#')[0]!==actor)throw Error('signature key owner mismatch');const remote=await actorJson(actor);if(!validActor(remote,actor))throw Error('remote actor public key invalid');const key=await crypto.subtle.importKey('spki',pem(remote.publicKey.publicKeyPem),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const u=new URL(req.url),lines:string[]=[];for(const h of p.headers.toLowerCase().split(/\s+/).filter(Boolean)){if(h==='(request-target)')lines.push(`(request-target): ${req.method.toLowerCase()} ${u.pathname}${u.search}`);else if(h==='host')lines.push(`host: ${u.host}`);else{const value=req.headers.get(h);if(value===null)throw Error(`signed header missing: ${h}`);lines.push(`${h}: ${value}`)}}if(!await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,ub64(p.signature),new TextEncoder().encode(lines.join('\n'))))throw Error('HTTP signature invalid')}
async function verifyRfc(req:Request,raw:string,actor:string){const input=req.headers.get('signature-input'),sig=req.headers.get('signature'),digest=req.headers.get('content-digest');if(!input||!sig||!digest)throw Error('missing RFC9421 signature headers');const m=input.match(/^sig1=(\([^)]*\))(.*)$/);if(!m)throw Error('malformed Signature-Input');const components=[...m[1].matchAll(/"([^"]+)"/g)].map(x=>x[1]);const params=m[1]+m[2];const created=Number(m[2].match(/;created=(\d+)/)?.[1]||0);const keyId=m[2].match(/;keyid="([^"]+)"/)?.[1]||'';const alg=m[2].match(/;alg="([^"]+)"/)?.[1]||'';if(alg!=='rsa-v1_5-sha256'||keyId.split('#')[0]!==actor||Math.abs(Date.now()/1000-created)>300||!components.includes('@method')||!components.includes('@target-uri')||!components.includes('content-digest'))throw Error('invalid RFC9421 signature parameters');const dm=digest.match(/^sha-256=:([^:]+):$/i);const sm=sig.match(/^sig1=:([^:]+):$/);if(!dm||!sm)throw Error('invalid RFC9421 digest/signature');const expected=b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)));if(dm[1]!==expected)throw Error('Content-Digest mismatch');const remote=await actorJson(actor);if(!validActor(remote,actor))throw Error('remote actor public key invalid');const key=await crypto.subtle.importKey('spki',pem(remote.publicKey.publicKeyPem),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const base=`"@method": ${req.method}\n"@target-uri": ${new URL(req.url).toString()}\n"content-digest": ${digest}\n"@signature-params": ${params}`;if(!await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,ub64(sm[1]),new TextEncoder().encode(base)))throw Error('RFC9421 signature invalid')}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});try{if(req.method==='GET'){const u=new URL(req.url);const r=await fetch(`${API}${u.pathname}${u.search}`,{headers:req.headers});return new Response(await r.text(),{status:r.status,headers:r.headers})}if(req.method!=='POST')return new Response('Method Not Allowed',{status:405,headers:CORS});const raw=await req.text();if(!raw||raw.length>2000000)throw Error('invalid activity body');const activity=JSON.parse(raw);const actor=uri(activity.actor);if(!actor.startsWith('https://'))throw Error('HTTPS actor required');if(req.headers.get('signature-input'))await verifyRfc(req,raw,actor);else await verifyLegacy(req,raw,actor);const h=new Headers(req.headers);h.set('Authorization',`Bearer ${SERVICE}`);h.set('apikey',SERVICE);h.set('x-testagram-edge-verified','true');h.set('x-testagram-verified-actor',actor);const r=await fetch(INBOX,{method:'POST',headers:h,body:raw});return new Response(await r.text(),{status:r.status,headers:r.headers})}catch(e){return new Response(JSON.stringify({error:e instanceof Error?e.message:'Federation verification failed'}),{status:401,headers:{...CORS,'Content-Type':'application/json'}})}});