import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const URL_BASE=Deno.env.get("SUPABASE_URL")!;const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")!;const db=createClient(URL_BASE,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const ORIGIN="https://testagram.site";const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"accept,content-type,date,digest,signature","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...CORS,"Content-Type":"application/activity+json; charset=utf-8"}});
async function actor(username:string){const {data:a}=await db.from("activitypub_actors").select("*").eq("username",username).maybeSingle();if(!a)return null;const {data:p}=await db.from("profiles").select("display_name,bio,avatar_url").eq("id",a.user_id).maybeSingle();const {data:k}=await db.from("activitypub_keys").select("public_key_pem,key_id").eq("user_id",a.user_id).maybeSingle();return {a,p,k};}
async function outbox(username:string){const x=await actor(username);if(!x)return null;const {data}=await db.from("posts").select("id,content,created_at").eq("author_id",x.a.user_id).is("deleted_at",null).order("created_at",{ascending:false}).limit(30);const items=(data||[]).map((p:any)=>{const id=x.a.actor_id+"/statuses/"+p.id;return {"@context":"https://www.w3.org/ns/activitystreams",id:id+"/activity",type:"Create",actor:x.a.actor_id,published:p.created_at,object:{id,type:"Note",attributedTo:x.a.actor_id,content:p.content||"",published:p.created_at,url:id,to:["https://www.w3.org/ns/activitystreams#Public"],cc:[x.a.actor_id+"/followers"]}}});return {"@context":"https://www.w3.org/ns/activitystreams",id:x.a.outbox_url,type:"OrderedCollection",totalItems:items.length,orderedItems:items};}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});try{const u=new URL(req.url),path=u.pathname.replace(/^\/+/,"").split("/");
if(path[0]===".well-known"&&path[1]==="webfinger"){const r=u.searchParams.get("resource")||"";const m=r.match(/^acct:([^@]+)@(.+)$/i);if(!m||m[2].toLowerCase()!=="testagram.site")return json({error:"not found"},404);const x=await actor(m[1]);if(!x)return json({error:"not found"},404);return json({subject:r,aliases:[x.a.actor_id],links:[{rel:"self",type:"application/activity+json",href:x.a.actor_id},{rel:"http://webfinger.net/rel/profile-page",type:"text/html",href:x.a.actor_id}]});}
if(path[0]==="users"&&path[1]){const x=await actor(decodeURIComponent(path[1]));if(!x)return json({error:"not found"},404);if(path.length===2)return json({"@context":["https://www.w3.org/ns/activitystreams","https://w3id.org/security/v1"],id:x.a.actor_id,type:"Person",preferredUsername:x.a.username,name:x.p?.display_name||x.a.username,summary:x.p?.bio||"",url:x.a.actor_id,inbox:x.a.inbox_url,outbox:x.a.outbox_url,followers:x.a.followers_url,following:x.a.following_url,publicKey:{id:x.a.actor_id+"#main-key",owner:x.a.actor_id,publicKeyPem:x.k?.public_key_pem||""},icon:x.p?.avatar_url?{type:"Image",url:x.p.avatar_url}:undefined});
if(path[2]==="outbox")return json(await outbox(x.a.username));
if(path[2]==="followers"||path[2]==="following")return json({"@context":"https://www.w3.org/ns/activitystreams",id:x.a.actor_id+"/"+path[2],type:"OrderedCollection",totalItems:0,orderedItems:[]});
if(path[2]==="statuses"&&path[3]){const {data:p}=await db.from("posts").select("id,content,created_at").eq("id",path[3]).eq("author_id",x.a.user_id).maybeSingle();if(!p)return json({error:"not found"},404);const id=x.a.actor_id+"/statuses/"+p.id;return json({"@context":"https://www.w3.org/ns/activitystreams",id,type:"Note",attributedTo:x.a.actor_id,content:p.content||"",published:p.created_at,url:id,to:["https://www.w3.org/ns/activitystreams#Public"],cc:[x.a.actor_id+"/followers"]});}
if(path[2]==="inbox"){if(req.method!=="POST")return json({"@context":"https://www.w3.org/ns/activitystreams",id:x.a.inbox_url,type:"OrderedCollection",totalItems:0,orderedItems:[]});const payload=await req.json();await db.from("activitypub_inbox").insert({local_user_id:x.a.user_id,activity_type:String(payload.type||"Unknown"),actor_url:String(payload.actor||""),object_url:String(typeof payload.object==="string"?payload.object:payload.object?.id||""),payload,processed:false});return new Response("",{status:202,headers:CORS});}}
return json({error:"not found"},404);}catch(e){return json({error:e instanceof Error?e.message:"failed"},500)}});