import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const ROOT=Deno.env.get('FEDERATION_PUBLIC_ORIGIN')||'https://federation.testagram.site';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SUPABASE_SECRET_KEY')||'';
const db=createClient(SUPABASE_URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const AP='https://www.w3.org/ns/activitystreams',SEC='https://w3id.org/security/v1',TOOT='http://joinmastodon.org/ns#';
const H={'Content-Type':'application/activity+json; charset=utf-8','Access-Control-Allow-Origin':'*','Cache-Control':'public, max-age=60'};
const json=(v:unknown,s=200,extra:Record<string,string>={})=>new Response(JSON.stringify(v),{status:s,headers:{...H,...extra}});
const str=(v:unknown)=>typeof v==='string'?v:'';const uri=(v:unknown)=>typeof v==='string'?v:v&&typeof v==='object'?str((v as any).id):'';
const context=[AP,SEC,{toot:TOOT,discoverable:'toot:discoverable',indexable:'toot:indexable',featured:'toot:featured'}];
async function actor(username:string){
  const r=await db.from('federated_actors').select('*').eq('username',username).maybeSingle();
  if(r.error)throw r.error;
  if(r.data)return r.data;
  const p=await db.from('profiles').select('id,username,display_name,bio,avatar_url').eq('username',username).maybeSingle();
  if(p.error)throw p.error;
  if(!p.data)return null;
  const k=await db.from('activitypub_keys').select('public_key_pem,key_id').eq('user_id',p.data.id).maybeSingle();
  const id=`${ROOT}/users/${encodeURIComponent(username)}`;
  const row={user_id:p.data.id,actor_uri:id,username:p.data.username,domain:new URL(ROOT).hostname,display_name:p.data.display_name,bio:p.data.bio,avatar_url:p.data.avatar_url,inbox_url:`${id}/inbox`,outbox_url:`${id}/outbox`,followers_url:`${id}/followers`,following_url:`${id}/following`,public_key_pem:k.data?.public_key_pem||null,public_key_id:k.data?.key_id||`${id}#main-key`,fetched_at:new Date().toISOString(),updated_at:new Date().toISOString(),raw_actor:{}};
  const up=await db.from('federated_actors').upsert(row,{onConflict:'actor_uri'}).select('*').single();
  return up.data;
}
function actorJson(a:any){const id=str(a?.actor_url||a?.uri)||`${ROOT}/users/${encodeURIComponent(a.username||a.preferred_username)}`,u=str(a?.username||a?.preferred_username),inbox=str(a?.inbox_url)||`${id}/inbox`;return {'@context':context,id,type:str(a?.actor_type)||'Person',preferredUsername:u,name:str(a?.display_name)||u,summary:str(a?.summary),url:id,inbox,outbox:str(a?.outbox_url)||`${id}/outbox`,followers:str(a?.followers_url)||`${id}/followers`,following:str(a?.following_url)||`${id}/following`,endpoints:{sharedInbox:`${ROOT}/inbox`},discoverable:a?.discoverable!==false,indexable:true,manuallyApprovesFollowers:a?.locked===true,publicKey:{id:str(a?.public_key_id)||`${id}#main-key`,owner:id,publicKeyPem:str(a?.public_key_pem)},...(a?.avatar_url?{icon:{type:'Image',mediaType:'image/*',url:a.avatar_url}}:{}),...(a?.header_url?{image:{type:'Image',mediaType:'image/*',url:a.header_url}}:{})};}
function noteActivity(row:any){const id=str(row.uri),published=str(row.published_at)||new Date().toISOString(),actor=str(row.actor_uri);const object={'@context':AP,id,type:str(row.object_type)||'Note',attributedTo:actor,content:str(row.content),summary:str(row.summary)||undefined,published,updated:str(row.updated_at)||published,url:str(row.url)||id,to:[`${AP}#Public`],cc:actor?[`${actor}/followers`]:[],sensitive:!!row.sensitive,...(row.in_reply_to_uri?{inReplyTo:row.in_reply_to_uri}:{}),...(Array.isArray(row.attachments)&&row.attachments.length?{attachment:row.attachments}:{}),...(Array.isArray(row.tags)&&row.tags.length?{tag:row.tags}:{})};return {'@context':AP,id:`${id}/activity`,type:'Create',actor,published,to:object.to,cc:object.cc,object};}
function decodeCursor(v:string|null){if(!v)return null;try{return JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(v),c=>c.charCodeAt(0))))}catch{return null}}
function encodeCursor(v:any){return btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(v))));}
async function outbox(a:any,u:URL){const limit=Math.min(Math.max(Number(u.searchParams.get('limit')||20),1),40),cursor=decodeCursor(u.searchParams.get('cursor'));let q=db.from('federated_objects').select('*',{count:'exact'}).eq('actor_uri',a.actor_url||a.uri).is('deleted_at',null).eq('tombstone',false).order('published_at',{ascending:false,nullsFirst:false}).order('uri',{ascending:false}).limit(limit+1);if(cursor?.published_at&&cursor?.uri)q=q.or(`published_at.lt.${cursor.published_at},and(published_at.eq.${cursor.published_at},uri.lt.${cursor.uri})`);const r=await q;if(r.error)throw r.error;const rows=r.data||[],has=rows.length>limit,items=rows.slice(0,limit).map(noteActivity),last=rows[limit-1];const next=has&&last?`${a.actor_url||a.uri}/outbox?limit=${limit}&cursor=${encodeURIComponent(encodeCursor({published_at:last.published_at,uri:last.uri}))}`:null;return json({'@context':AP,id:`${a.actor_url||a.uri}/outbox`,type:'OrderedCollectionPage',partOf:`${a.actor_url||a.uri}/outbox`,totalItems:r.count||items.length,orderedItems:items,...(next?{next}:{})});}
async function collection(a:any,kind:string,u:URL){const relation=kind==='followers'?'follower':'following',limit=Math.min(Math.max(Number(u.searchParams.get('limit')||40),1),100),cursor=decodeCursor(u.searchParams.get('cursor'));let q=db.from('federated_relationships').select('remote_actor_uri,created_at,id',{count:'exact'}).eq('local_user_id',a.user_id).eq('relationship',relation).in('state',['accepted','active']).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(limit+1);if(cursor?.created_at&&cursor?.id)q=q.or(`created_at.lt.${cursor.created_at},and(created_at.eq.${cursor.created_at},id.lt.${cursor.id})`);const r=await q;if(r.error)throw r.error;const rows=r.data||[],has=rows.length>limit,items=rows.slice(0,limit).map((x:any)=>x.remote_actor_uri),last=rows[limit-1] as any;const next=has&&last?`${a.actor_url||a.uri}/${kind}?limit=${limit}&cursor=${encodeURIComponent(encodeCursor({created_at:last.created_at,id:last.id}))}`:null;return json({'@context':AP,id:`${a.actor_url||a.uri}/${kind}`,type:'OrderedCollectionPage',partOf:`${a.actor_url||a.uri}/${kind}`,totalItems:r.count||items.length,orderedItems:items,...(next?{next}:{})});}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'content-type,accept,date,digest,signature,signature-input,content-digest,host'}});try{const u=new URL(req.url);if(req.method==='POST'){const raw=await req.text();const r=await fetch(`${SUPABASE_URL}/functions/v1/federation-inbox`,{method:'POST',headers:req.headers,body:raw});return new Response(await r.text(),{status:r.status,headers:r.headers});}if(req.method!=='GET')return json({error:'GET or POST required'},405,{'Content-Type':'application/json'});if(u.pathname==='/.well-known/webfinger'){const resource=u.searchParams.get('resource')||'',m=resource.match(/^acct:([^@]+)@([^@]+)$/i);if(!m)return json({error:'Invalid resource'},400,{'Content-Type':'application/jrd+json'});if(m[2].toLowerCase()!==new URL(ROOT).hostname.toLowerCase())return json({error:'Unknown host'},404,{'Content-Type':'application/jrd+json'});const a=await actor(m[1]);if(!a)return json({error:'Actor not found'},404,{'Content-Type':'application/jrd+json'});const id=str(a.actor_url||a.uri);return json({subject:`acct:${m[1]}@${new URL(ROOT).hostname}`,aliases:[id],links:[{rel:'self',type:'application/activity+json',href:id},{rel:'http://webfinger.net/rel/profile-page',type:'text/html',href:id}]},200,{'Content-Type':'application/jrd+json; charset=utf-8'});}if(u.pathname==='/.well-known/nodeinfo')return json({links:[{rel:'http://nodeinfo.diaspora.software/ns/schema/2.0',href:`${ROOT}/nodeinfo/2.0`}]},200,{'Content-Type':'application/json'});if(u.pathname==='/nodeinfo/2.0'){const [users,posts]=await Promise.all([db.from('profiles').select('id',{count:'exact',head:true}),db.from('posts').select('id',{count:'exact',head:true}).is('deleted_at',null)]);return json({version:'2.0',software:{name:'testagram',version:'1.0.0'},protocols:['activitypub'],usage:{users:{total:users.count||0,activeMonth:users.count||0,activeHalfyear:users.count||0},localPosts:posts.count||0},openRegistrations:true,metadata:{}},200,{'Content-Type':'application/json'});}const m=u.pathname.match(/^\/users\/([^/]+)(?:\/(followers|following|outbox))?$/);if(m){const a=await actor(decodeURIComponent(m[1]));if(!a)return json({error:'Actor not found'},404,{'Content-Type':'application/json'});if(!m[2])return json(actorJson(a));if(m[2]==='outbox')return outbox(a,u);return collection(a,m[2],u);}return json({error:'Not found'},404,{'Content-Type':'application/json'});}catch(e){console.error('[mastodon-federation]',e);return json({error:e instanceof Error?e.message:'Federation endpoint failed'},500,{'Content-Type':'application/json','Cache-Control':'no-store'});}});
