import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { TopBar } from '@/components/layout/TopBar';
import { PageAdBanner } from '@/components/features/AdSenseAd';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/lib/supabase';
import { useSEO } from '@/hooks/useSEO';
import { toast } from 'sonner';
import { BarChart3, CheckCircle2, DollarSign, Image as ImageIcon, Loader2, Megaphone, Target, Users } from 'lucide-react';
import { formatNumber } from '@/lib/utils';
import { CreditBoostDialog } from '@/components/features/CreditBoostDialog';

const TYPES = [['reach','Reach','Maximize impressions'],['engagement','Engagement','Drive interactions'],['conversions','Conversions','Drive profile visits & follows'],['video_views','Video Views','Maximize video play-throughs']] as const;

export default function BoostCreatePage() {
  useSEO({ noindex: true, title: 'Create Boost Campaign', url: '/boost-create' });
  const { user } = useAuth(); const navigate = useNavigate(); const [params] = useSearchParams();
  const postId=params.get('post_id')??''; const [post,setPost]=useState<any>(null); const [wallet,setWallet]=useState(0);\n  const [creditDialogOpen,setCreditDialogOpen]=useState(false);
  const [type,setType]=useState('reach'); const [daily,setDaily]=useState(100); const [days,setDays]=useState(7);
  const [ageMin,setAgeMin]=useState(18); const [ageMax,setAgeMax]=useState(55); const [interests,setInterests]=useState<string[]>([]);
  const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const total=daily*days;
  const cpm=({reach:8,engagement:12,conversions:20,video_views:6} as Record<string,number>)[type]??8;
  const ctr=({reach:.012,engagement:.025,conversions:.045,video_views:.018} as Record<string,number>)[type]??.012;
  const impressions=Math.round(total/cpm*1000);
  useEffect(()=>{if(!user){navigate('/auth');return;}if(!postId){toast.error('Choose a post to boost.');navigate('/');return;}void load();},[user?.id,postId]);
  const load=async()=>{const [{data:p},{data:w}]=await Promise.all([supabase.from('posts').select('id,content,image_url,video_url,is_video,views_count,likes_count').eq('id',postId).maybeSingle(),supabase.rpc('get_my_wallet')]);setPost(p);setWallet(Number(w?.balance??0));};
  const launch=async()=>{if(!user||total<=0)return;if(wallet<total){toast.error(`Insufficient Wallet balance. You need KES ${(total-wallet).toLocaleString()} more.`);return;}setBusy(true);
    const {data,error}=await supabase.rpc('create_boost_campaign',{p_post_id:postId,p_boost_type:type,p_budget_minor:total*100,p_starts_at:new Date().toISOString(),p_ends_at:new Date(Date.now()+days*86400000).toISOString(),p_target_audience:{age_min:ageMin,age_max:ageMax,interests}});
    setBusy(false); if(error){toast.error(error.message);return;} if(!data){toast.error('Boost campaign was not created.');return;} setDone(true);
    toast.success('Boost funded and launched from your Wallet.'); setTimeout(()=>navigate(`/boost-analytics/${postId}`),1000);
  };
  const options=['Technology','Sports','Music','Art','Food','Travel','Fashion','Gaming','Finance','Education','Business','Entertainment'];
  const selectedLabel=useMemo(()=>TYPES.find(x=>x[0]===type)?.[1]??type,[type]);
  if(done)return <div className="min-h-screen flex flex-col items-center justify-center gap-4 p-6 text-center"><CheckCircle2 className="w-20 h-20 text-green-500"/><h1 className="text-2xl font-black">Boost funded</h1><p className="text-muted-foreground">KES {total.toLocaleString()} moved from your Wallet into the Testagram platform account and your campaign is live.</p></div>;
  return <div className="min-h-screen bg-background pb-20"><TopBar title="Create Boost Campaign" showBack/><PageAdBanner/><main className="max-w-2xl mx-auto p-4 space-y-5">
    <section className="rounded-2xl border border-primary/20 bg-primary/5 p-5"><div className="flex items-center gap-3"><Megaphone className="w-7 h-7 text-primary"/><div><h1 className="text-xl font-black">Boost a post</h1><p className="text-xs text-muted-foreground">Wallet-funded, server-authoritative campaign billing.</p></div></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setCreditDialogOpen(true)} className="rounded-xl border border-primary/30 bg-background p-3 text-left hover:bg-primary/5"><strong className="block text-sm">Use Credits</strong><span className="text-[11px] text-muted-foreground">Internal promotion balance</span></button><button onClick={()=>document.getElementById('wallet-boost-budget')?.scrollIntoView({behavior:'smooth'})} className="rounded-xl border p-3 text-left hover:bg-muted/50"><strong className="block text-sm">Use Wallet</strong><span className="text-[11px] text-muted-foreground">KES campaign budget</span></button></div><div className="mt-4 flex justify-between rounded-xl bg-background/70 p-3"><span className="text-sm text-muted-foreground">Wallet balance</span><strong className="text-green-600">KES {wallet.toLocaleString()}</strong></div></section>
    {post&&<section className="rounded-2xl border p-4 flex gap-3"><div className="w-16 h-16 rounded-xl overflow-hidden bg-muted shrink-0">{post.image_url?<img src={post.image_url} className="w-full h-full object-cover" alt=""/>:post.video_url?<video src={post.video_url} className="w-full h-full object-cover" muted playsInline/>:<div className="w-full h-full flex items-center justify-center"><ImageIcon/></div>}</div><div><p className="font-semibold line-clamp-2">{post.content||'Post'}</p><p className="text-xs text-muted-foreground mt-1">{formatNumber(post.views_count??0)} views · {formatNumber(post.likes_count??0)} likes</p></div></section>}
    <section className="rounded-2xl border p-5 space-y-3"><h2 className="font-bold flex items-center gap-2"><Target className="w-4 h-4"/>Objective</h2><div className="grid grid-cols-2 gap-2">{TYPES.map(([id,label,desc])=><button key={id} onClick={()=>setType(id)} className={`rounded-xl border p-3 text-left ${type===id?'border-primary bg-primary/10':'border-border'}`}><p className="font-bold text-sm">{label}</p><p className="text-[11px] text-muted-foreground mt-1">{desc}</p></button>)}</div></section>
    <section id="wallet-boost-budget" className="rounded-2xl border p-5 space-y-5"><h2 className="font-bold flex items-center gap-2"><DollarSign className="w-4 h-4"/>Budget</h2><div><div className="flex justify-between text-sm"><span>Daily budget</span><strong>KES {daily.toLocaleString()}</strong></div><input className="w-full mt-2" type="range" min="50" max="5000" step="50" value={daily} onChange={e=>setDaily(Number(e.target.value))}/></div><div><div className="flex justify-between text-sm"><span>Duration</span><strong>{days} days</strong></div><input className="w-full mt-2" type="range" min="1" max="30" value={days} onChange={e=>setDays(Number(e.target.value))}/></div></section>
    <section className="rounded-2xl border p-5 space-y-4"><h2 className="font-bold flex items-center gap-2"><Users className="w-4 h-4"/>Audience</h2><div className="grid grid-cols-2 gap-3"><label className="text-xs">Min age<input className="w-full" type="range" min="13" max={ageMax-1} value={ageMin} onChange={e=>setAgeMin(Number(e.target.value))}/><b>{ageMin}</b></label><label className="text-xs">Max age<input className="w-full" type="range" min={ageMin+1} max="65" value={ageMax} onChange={e=>setAgeMax(Number(e.target.value))}/><b>{ageMax}</b></label></div><div className="flex flex-wrap gap-2">{options.map(x=>{const on=interests.includes(x);return <button key={x} onClick={()=>setInterests(v=>on?v.filter(i=>i!==x):v.length<5?[...v,x]:v)} className={`rounded-full border px-3 py-1.5 text-xs ${on?'border-primary bg-primary/10 text-primary':''}`}>{x}</button>})}</div></section>
    <section className="rounded-2xl border border-primary/20 bg-primary/5 p-5"><h2 className="font-bold mb-3 flex items-center gap-2"><BarChart3 className="w-4 h-4"/>Summary</h2><div className="grid grid-cols-3 gap-2 text-center"><div><strong className="block">KES {total.toLocaleString()}</strong><span className="text-[10px] text-muted-foreground">Total budget</span></div><div><strong className="block">{formatNumber(impressions)}</strong><span className="text-[10px] text-muted-foreground">Est. impressions</span></div><div><strong className="block">{(ctr*100).toFixed(1)}%</strong><span className="text-[10px] text-muted-foreground">Est. CTR</span></div></div><p className="text-xs text-muted-foreground mt-4">Objective: <b>{selectedLabel}</b> · KES {daily.toLocaleString()}/day · {days} days</p><button onClick={launch} disabled={busy||wallet<total} className="mt-4 w-full rounded-xl bg-primary text-primary-foreground py-3 font-bold disabled:opacity-50">{busy?<><Loader2 className="inline w-4 h-4 animate-spin mr-2"/>Funding…</>:wallet<total?'Top up Wallet first':'Fund & Launch Boost'}</button></section>
  </main></div>;
}