import { useEffect, useState } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { TopBar } from '@/components/layout/TopBar';
import { toast } from 'sonner';
import { Globe2, Shield, Filter, Users, Plus, Trash2, Loader2, Rss, Quote, Hash } from 'lucide-react';

type Tab='feeds'|'filters'|'domains'|'collections'|'tags'|'profile';
export default function FediverseParityPage(){
 const {user}=useAuth(); const navigate=useNavigate(); const [tab,setTab]=useState<Tab>('feeds'); const [loading,setLoading]=useState(true);
 const [feeds,setFeeds]=useState<any[]>([]),[filters,setFilters]=useState<any[]>([]),[domains,setDomains]=useState<any[]>([]),[collections,setCollections]=useState<any[]>([]),[featuredTags,setFeaturedTags]=useState<any[]>([]);
 const [name,setName]=useState(''),[query,setQuery]=useState(''),[phrase,setPhrase]=useState(''),[domain,setDomain]=useState(''),[collection,setCollection]=useState(''),[tag,setTag]=useState('');
 const [policy,setPolicy]=useState('public'),[saving,setSaving]=useState(false);
 const load=async()=>{if(!user)return;setLoading(true);
  const [f,fi,d,c,p,tags]=await Promise.all([
   supabase.from('federated_custom_discovery_feeds').select('*').eq('user_id',user.id).order('updated_at',{ascending:false}),
   supabase.from('fediverse_content_filters').select('*').eq('user_id',user.id).order('created_at',{ascending:false}),
   supabase.from('fediverse_domain_blocks').select('*').eq('user_id',user.id).order('created_at',{ascending:false}),
   supabase.from('fediverse_profile_collections').select('*,fediverse_profile_collection_members(*)').eq('user_id',user.id).order('created_at',{ascending:false}),
   supabase.from('profiles').select('fediverse_quote_policy').eq('id',user.id).maybeSingle(),
   supabase.from('fediverse_featured_tags').select('*').eq('user_id',user.id).order('created_at',{ascending:false})
  ]);
  if(f.error||fi.error||d.error||c.error||p.error||tags.error) toast.error((f.error||fi.error||d.error||c.error||p.error||tags.error)?.message||'Failed to load Fediverse settings');
  setFeeds(f.data??[]);setFilters(fi.data??[]);setDomains(d.data??[]);setCollections(c.data??[]);setFeaturedTags(tags.data??[]);setPolicy(p.data?.fediverse_quote_policy??'public');setLoading(false);
 };
 useEffect(()=>{if(!user){navigate('/auth');return}void load()},[user?.id]);
 const addFeed=async()=>{if(!user||!name.trim())return;setSaving(true);const {data,error}=await supabase.from('federated_custom_discovery_feeds').insert({user_id:user.id,name:name.trim(),query:query.trim(),mode:'all'}).select().single();if(error)toast.error(error.message);else{setFeeds(v=>[data,...v]);setName('');setQuery('');toast.success('Custom Fediverse feed created')}setSaving(false)};
 const addFilter=async()=>{if(!user||!phrase.trim())return;setSaving(true);const {data,error}=await supabase.from('fediverse_content_filters').insert({user_id:user.id,name:(name||phrase).trim(),phrase:phrase.trim(),action:'hide'}).select().single();if(error)toast.error(error.message);else{setFilters(v=>[data,...v]);setName('');setPhrase('');toast.success('Filter created')}setSaving(false)};
 const addDomain=async()=>{if(!user||!domain.trim())return;const clean=domain.trim().toLowerCase().replace(/^https?:\/\//,'').replace(/\/$/,'');const {data,error}=await supabase.from('fediverse_domain_blocks').insert({user_id:user.id,domain:clean}).select().single();if(error)toast.error(error.message);else{setDomains(v=>[data,...v]);setDomain('');toast.success('Domain blocked')}};
 const addTag=async()=>{if(!user||!tag.trim())return;const clean=tag.trim().replace(/^#/,'').toLowerCase();const {data,error}=await supabase.from('fediverse_featured_tags').insert({user_id:user.id,tag:clean}).select().single();if(error)toast.error(error.message);else{setFeaturedTags(v=>[data,...v]);setTag('');toast.success('Featured tag added')}};
 const addCollection=async()=>{if(!user||!collection.trim())return;const {data,error}=await supabase.from('fediverse_profile_collections').insert({user_id:user.id,name:collection.trim()}).select().single();if(error)toast.error(error.message);else{setCollections(v=>[data,...v]);setCollection('');toast.success('Collection created')}};
 const remove=async(table:string,id:string)=>{const {error}=await supabase.from(table).delete().eq('id',id);if(error)toast.error(error.message);else{if(table==='federated_custom_discovery_feeds')setFeeds(v=>v.filter(x=>x.id!==id));if(table==='fediverse_content_filters')setFilters(v=>v.filter(x=>x.id!==id));if(table==='fediverse_domain_blocks')setDomains(v=>v.filter(x=>x.id!==id));if(table==='fediverse_profile_collections')setCollections(v=>v.filter(x=>x.id!==id));if(table==='fediverse_featured_tags')setFeaturedTags(v=>v.filter(x=>x.id!==id));}};
 const savePolicy=async(v:string)=>{setPolicy(v);const {error}=await supabase.from('profiles').update({fediverse_quote_policy:v}).eq('id',user!.id);if(error)toast.error(error.message);else toast.success('Quote policy saved')};
 if(!user)return null;
 const tabs=[['feeds','Custom feeds',Rss],['filters','Filters',Filter],['domains','Domain blocks',Shield],['collections','Collections',Users],['tags','Featured tags',Hash],['profile','Quote policy',Quote]] as const;
 return <div className="min-h-screen bg-background pb-16"><TopBar title="Fediverse controls" showBack/><div className="max-w-2xl mx-auto">
  <div className="px-3 py-2 border-b border-border flex gap-1 overflow-x-auto">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 rounded-full text-xs font-semibold whitespace-nowrap flex items-center gap-1.5 ${tab===id?'bg-primary text-primary-foreground':'hover:bg-muted text-muted-foreground'}`}><Icon className="w-3.5 h-3.5"/>{label}</button>)}</div>
  {loading?<div className="py-20 flex justify-center"><Loader2 className="w-7 h-7 animate-spin text-primary"/></div>:
  <div className="p-4 space-y-4">
   {tab==='feeds'&&<><div className="rounded-2xl border border-border p-4"><h2 className="font-bold">Custom feeds</h2><p className="text-xs text-muted-foreground mt-1">Choose your own Fediverse algorithm instead of one global timeline. This mirrors Mastodon custom feeds and Bluesky custom feeds.</p><div className="grid gap-2 mt-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Feed name" className="rounded-xl border bg-background px-3 py-2 text-sm"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Keywords, #hashtags, @handles, or instance" className="rounded-xl border bg-background px-3 py-2 text-sm"/><button onClick={addFeed} disabled={saving||!name.trim()} className="rounded-xl bg-primary text-primary-foreground py-2 font-semibold disabled:opacity-50"><Plus className="inline w-4 h-4 mr-1"/>Create feed</button></div></div>{feeds.map(x=><div key={x.id} className="border rounded-xl p-3 flex gap-3"><Rss className="w-4 h-4 text-primary mt-1"/><div className="flex-1"><b>{x.name}</b><p className="text-xs text-muted-foreground">{x.query||'All public Fediverse content'}</p></div><button onClick={()=>void remove('federated_custom_discovery_feeds',x.id)}><Trash2 className="w-4 h-4 text-muted-foreground"/></button></div>)}</>}
   {tab==='filters'&&<><div className="rounded-2xl border p-4"><h2 className="font-bold">Keyword filters</h2><p className="text-xs text-muted-foreground mt-1">Hide unwanted words or phrases from Fediverse surfaces.</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="Filter name" className="w-full mt-3 rounded-xl border px-3 py-2 text-sm"/><input value={phrase} onChange={e=>setPhrase(e.target.value)} placeholder="Word or phrase" className="w-full mt-2 rounded-xl border px-3 py-2 text-sm"/><button onClick={addFilter} disabled={saving||!phrase.trim()} className="w-full mt-2 rounded-xl bg-primary text-primary-foreground py-2 font-semibold"><Plus className="inline w-4 h-4 mr-1"/>Add filter</button></div>{filters.map(x=><div key={x.id} className="border rounded-xl p-3 flex gap-3"><Filter className="w-4 h-4 mt-1"/><div className="flex-1"><b>{x.name}</b><p className="text-xs text-muted-foreground">{x.phrase}</p></div><button onClick={()=>void remove('fediverse_content_filters',x.id)}><Trash2 className="w-4 h-4 text-muted-foreground"/></button></div>)}</>}
   {tab==='domains'&&<><div className="rounded-2xl border p-4"><h2 className="font-bold">Blocked instances</h2><p className="text-xs text-muted-foreground mt-1">Hide remote content from an entire domain.</p><div className="flex gap-2 mt-3"><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="example.social" className="flex-1 rounded-xl border px-3 py-2 text-sm"/><button onClick={addDomain} disabled={!domain.trim()} className="px-4 rounded-xl bg-primary text-primary-foreground"><Plus className="w-4 h-4"/></button></div></div>{domains.map(x=><div key={x.id} className="border rounded-xl p-3 flex items-center gap-3"><Globe2 className="w-4 h-4"/><span className="flex-1 font-semibold">{x.domain}</span><button onClick={()=>void remove('fediverse_domain_blocks',x.id)}><Trash2 className="w-4 h-4 text-muted-foreground"/></button></div>)}</>}
   {tab==='collections'&&<><div className="rounded-2xl border p-4"><h2 className="font-bold">Profile collections</h2><p className="text-xs text-muted-foreground mt-1">Curate remote accounts into shareable groups.</p><div className="flex gap-2 mt-3"><input value={collection} onChange={e=>setCollection(e.target.value)} placeholder="Collection name" className="flex-1 rounded-xl border px-3 py-2 text-sm"/><button onClick={addCollection} disabled={!collection.trim()} className="px-4 rounded-xl bg-primary text-primary-foreground"><Plus className="w-4 h-4"/></button></div></div>{collections.map(x=><div key={x.id} className="border rounded-xl p-3 flex gap-3"><Users className="w-4 h-4 mt-1"/><div className="flex-1"><b>{x.name}</b><p className="text-xs text-muted-foreground">{x.fediverse_profile_collection_members?.length??0} accounts</p></div><button onClick={()=>void remove('fediverse_profile_collections',x.id)}><Trash2 className="w-4 h-4 text-muted-foreground"/></button></div>)}</>}
   {tab==='tags'&&<><div className="rounded-2xl border p-4"><h2 className="font-bold">Featured hashtags</h2><p className="text-xs text-muted-foreground mt-1">Pin hashtags to your profile so remote visitors can discover the topics you follow.</p><div className="flex gap-2 mt-3"><input value={tag} onChange={e=>setTag(e.target.value)} placeholder="#technology" className="flex-1 rounded-xl border px-3 py-2 text-sm"/><button onClick={addTag} disabled={!tag.trim()} className="px-4 rounded-xl bg-primary text-primary-foreground"><Plus className="w-4 h-4"/></button></div></div>{featuredTags.map(x=><div key={x.id} className="border rounded-xl p-3 flex items-center gap-3"><Hash className="w-4 h-4"/><span className="flex-1 font-semibold">#{x.tag}</span><button onClick={()=>void remove('fediverse_featured_tags',x.id)}><Trash2 className="w-4 h-4 text-muted-foreground"/></button></div>)}</>}{tab==='profile'&&<div className="rounded-2xl border p-4"><h2 className="font-bold">Quote policy</h2><p className="text-xs text-muted-foreground mt-1">Mastodon 4.5+ supports explicit quote permissions and consent-aware quote handling.</p><div className="grid gap-2 mt-4">{[['public','Anyone'],['followers','Followers only'],['nobody','Just me']].map(([v,l])=><button key={v} onClick={()=>void savePolicy(v)} className={`rounded-xl border p-3 text-left ${policy===v?'border-primary bg-primary/5':''}`}><b>{l}</b><p className="text-xs text-muted-foreground">{v==='public'?'Remote accounts may quote public posts.':v==='followers'?'Only followers may quote.':'Only you may quote.'}</p></button>)}</div></div>}
   <div className="rounded-xl bg-muted/40 p-3 text-xs text-muted-foreground"><Hash className="inline w-3.5 h-3.5 mr-1"/>Followed hashtags, polls, bookmarks, GIFs, video, scheduling, notifications, lists and profile verification already exist elsewhere in Testagram; this page consolidates the Fediverse-specific controls that were missing.</div>
  </div>}
 </div></div>;
}