import { useEffect,useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Loader2,Megaphone,BarChart3,WalletCards,Plus } from 'lucide-react';
import { toast } from 'sonner';
type Campaign={id:string;name:string;status:string;payment_status:string;currency:string;lifetime_budget_micros:number;starts_at:string;ends_at:string|null;created_at:string};type Creative={id:string;campaign_id:string;headline:string;asset_url:string|null;click_through_url:string|null};type Stats={impressions:number;clicks:number;spendMicros:number};const money=(micros:number,currency='KES')=>`${currency} ${(Number(micros||0)/1_000_000).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;const label=(status:string,payment:string)=>payment!=='funded'?'Awaiting payment':status.replace(/_/g,' ');
export default function MyAdsPage(){const navigate=useNavigate();const [loading,setLoading]=useState(true);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [creatives,setCreatives]=useState<Creative[]>([]);const [stats,setStats]=useState<Record<string,Stats>>({});useEffect(()=>{let cancelled=false;(async()=>{try{const {data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error('Authentication required');const {data:advertisers,error:ae}=await supabase.from('testagram_advertisers').select('id').eq('owner_user_id',auth.user.id);if(ae)throw ae;const advertiserIds=(advertisers??[]).map(a=>a.id);if(!advertiserIds.length){if(!cancelled){setCampaigns([]);setCreatives([]);setStats({});}return;}const {data:rows,error:ce}=await supabase.from('testagram_ad_campaigns').select('id,name,status,payment_status,currency,lifetime_budget_micros,starts_at,ends_at,created_at').in('advertiser_id',advertiserIds).order('created_at',{ascending:false});if(ce)throw ce;const list=(rows??[]) as Campaign[];const ids=list.map(c=>c.id);const {data:cs,error:cre}=ids.length?await supabase.from('testagram_ad_creatives').select('id,campaign_id,headline,asset_url,click_through_url').in('campaign_id',ids).order('created_at',{ascending:true}):{data:[],error:null};if(cre)throw cre;const next:Record<string,Stats>={};if(ids.length){const {data:imps,error:ie}=await supabase.from('testagram_ad_impressions').select('campaign_id,billable_micros,clicked').in('campaign_id',ids);if(ie)throw ie;for(const imp of imps??[]){const id=String(imp.campaign_id);const s=next[id]??{impressions:0,clicks:0,spendMicros:0};s.impressions++;if(imp.clicked)s.clicks++;s.spendMicros+=Number(imp.billable_micros??0);next[id]=s;}}if(!cancelled){setCampaigns(list);setCreatives((cs??[]) as Creative[]);setStats(next);}}catch(error){console.error('[MyAdsPage]',error);if(!cancelled)toast.error(error instanceof Error?error.message:'Failed to load your ads');}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true;};},[]);
if(loading)return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin"/></div>;return <div className="container mx-auto max-w-6xl space-y-6 p-4"><header className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">My Ads</h1><p className="text-muted-foreground">Manage your Testagram campaigns and monitor delivery.</p></div><Button onClick={()=>navigate('/create-ad')}><Plus className="mr-2 h-4 w-4"/>Create Ad</Button></header>{!campaigns.length?<Card><CardContent className="flex flex-col items-center gap-3 py-12 text-center"><Megaphone className="h-10 w-10"/><h2 className="text-lg font-semibold">No campaigns yet</h2><p className="text-sm text-muted-foreground">Create an ad campaign to start reaching Testagram users.</p><Button onClick={()=>navigate('/create-ad')}><Plus className="mr-2 h-4 w-4"/>Create your first ad</Button></CardContent></Card>:<div className="grid gap-4 md:grid-cols-2">{campaigns.map(campaign=>{const creative=creatives.find(c=>c.campaign_id===campaign.id);const s=stats[campaign.id]??{impressions:0,clicks:0,spendMicros:0};return <Card key={campaign.id}><CardHeader><div className="flex items-start justify-between gap-3"><div className="min-w-0"><CardTitle className="truncate">{campaign.name}</CardTitle>{creative?.headline&&<p className="mt-1 truncate text-sm text-muted-foreground">{creative.headline}</p>}</div><Badge variant={campaign.payment_status==='funded'?'default':'secondary'}>{label(campaign.status,campaign.payment_status)}</Badge></div>{creative?.asset_url&&<img src={creative.asset_url} alt="" className="max-h-56 w-full rounded-md object-cover"/>}</CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-3 gap-3 text-sm"><div className="rounded-md border p-3"><BarChart3 className="mb-1 h-4 w-4"/><strong>{s.impressions.toLocaleString()}</strong><div className="text-muted-foreground">Impressions</div></div><div className="rounded-md border p-3"><Megaphone className="mb-1 h-4 w-4"/><strong>{s.clicks.toLocaleString()}</strong><div className="text-muted-foreground">Clicks</div></div><div className="rounded-md border p-3"><WalletCards className="mb-1 h-4 w-4"/><strong>{money(s.spendMicros,campaign.currency)}</strong><div className="text-muted-foreground">Spend</div></div></div><div className="flex justify-between text-sm"><span className="text-muted-foreground">Budget</span><span className="font-medium">{money(campaign.lifetime_budget_micros,campaign.currency)}</span></div><div className="flex justify-between text-xs text-muted-foreground"><span>Starts {new Date(campaign.starts_at).toLocaleString()}</span><span>{campaign.ends_at?`Ends ${new Date(campaign.ends_at).toLocaleString()}`:'No end date'}</span></div>{creative?.click_through_url&&<Button variant="outline" asChild className="w-full"><a href={creative.click_through_url} target="_blank" rel="noreferrer">Open landing page</a></Button>}</CardContent></Card>;})}</div>}</div>;
}
