import { useEffect, useMemo, useRef, useState } from 'react';
import { VerifiedTick } from '@/components/ui/VerifiedTick';
import { Search, X, Clock3, Hash, AtSign, Sparkles, Users, Image as ImageIcon, ListFilter, Loader2, TrendingUp, Globe2, ChevronDown, Lock } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { TopBar } from '@/components/layout/TopBar';
import { Input } from '@/components/ui/input';
import { PostCard } from '@/components/features/PostCard';
import { formatNumber } from '@/lib/utils';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/lib/supabase';
import { toast } from 'sonner';
import { TestagramCapabilityClient, CapabilityClientError, type SearchDiscoveryPage } from '@/services/testagramCapabilityClient';
import * as federation from '@/api/federation';

const TABS=['Top','Latest','People','Media','Hashtags','Communities','Fediverse'];
const KEYWORDS=['technology','artificial intelligence','football','music','Kenya','Nairobi','business','gaming','science','creator economy','travel','news'];
const endpoint=(name:string)=>`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/${name}`;

function client(){return new TestagramCapabilityClient({endpoint:endpoint('capability-gateway'),getAccessToken:async()=>{const {data}=await supabase.auth.getSession();return data.session?.access_token??null},clientName:'testagram-search',clientVersion:'3',timeoutMs:12000});}

export default function SearchPageV3(){
 const {user}=useAuth(); const navigate=useNavigate(); const [params,setParams]=useSearchParams();
 const initial=params.get('q')??''; const [query,setQuery]=useState(initial); const [tab,setTab]=useState(params.get('tab')??'Top');
 const [data,setData]=useState<SearchDiscoveryPage>({users:[],hashtags:[],posts:[],communities:[],next_cursor:null});
 const [fediverse,setFediverse]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [suggestLoading,setSuggestLoading]=useState(false); const [suggest,setSuggest]=useState<SearchDiscoveryPage>({users:[],hashtags:[],posts:[],communities:[],next_cursor:null});
 const [showSuggest,setShowSuggest]=useState(false); const [recent,setRecent]=useState<string[]>([]); const [mediaOnly,setMediaOnly]=useState(false); const [verifiedOnly,setVerifiedOnly]=useState(false); const [sort,setSort]=useState('Relevance'); const [showFilters,setShowFilters]=useState(false);
 const [loadingMore,setLoadingMore]=useState(false); const [hasMore,setHasMore]=useState(true); const inputTimer=useRef<ReturnType<typeof setTimeout>|null>(null); const sentinel=useRef<HTMLDivElement|null>(null); const box=useRef<HTMLDivElement|null>(null);
 const api=useMemo(()=>client(),[]);
 useEffect(()=>{try{setRecent(JSON.parse(localStorage.getItem('tsocial_recent_searches')||'[]').slice(0,8))}catch{}},[]);
 useEffect(()=>{const close=(e:MouseEvent)=>{if(box.current&&!box.current.contains(e.target as Node))setShowSuggest(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 const saveRecent=(q:string)=>{const next=[q,...recent.filter(x=>x!==q)].slice(0,8);setRecent(next);try{localStorage.setItem('tsocial_recent_searches',JSON.stringify(next))}catch{}};
 const suggestFor=async(q:string)=>{if(!q.trim()){setSuggest({users:[],hashtags:[],posts:[],communities:[],next_cursor:null});return}setSuggestLoading(true);try{const token=q.trim().replace(/^[@#]/,'');const r=await api.searchDiscovery(endpoint('search-discovery'),token,'suggest',8);setSuggest(r)}catch(e){console.debug('[search-suggest]',e)}finally{setSuggestLoading(false)}};
 const run=async(q=query,nextTab=tab,append=false)=>{if(!q.trim())return;const clean=q.trim();if(!append){saveRecent(clean);setLoading(true);setHasMore(true);setData({users:[],hashtags:[],posts:[],communities:[],next_cursor:null});setFediverse([]);setParams({q:clean,tab:nextTab})}else setLoadingMore(true);
  try{const r=await api.searchDiscovery(endpoint('search-discovery'),clean,'search',50,append?data.next_cursor??undefined:undefined);
   // Search the complete Testagram graph as well: people, hashtags, communities, live Spaces and trends.
   const { data: global } = await supabase.rpc('search_everything',{p_query:clean,p_limit:50,p_cursor:append?data.next_cursor??null:null});
   if(global) setData(prev=>({
     users: global.users ?? prev.users, hashtags: global.hashtags ?? prev.hashtags,
     posts: append ? [...prev.posts,...(global.posts??[])] : (global.posts??prev.posts),
     communities: global.communities ?? prev.communities,
     next_cursor: r.next_cursor
   }));setData(prev=>append?{users:r.users,hashtags:r.hashtags,posts:[...prev.posts,...r.posts],communities:r.communities,next_cursor:r.next_cursor}:{...r});setHasMore(Boolean(r.next_cursor));
   if(nextTab==='Fediverse'||clean.startsWith('@')){try{const remote:any=await federation.search(clean.replace(/^@/,''),'users');const rows=Array.isArray(remote)?remote:remote?.accounts??remote?.users??remote?.data??[];setFediverse(rows.map((a:any)=>({actor_url:a.url??a.id,username:a.username??a.preferredUsername,domain:a.acct?.split('@')[1]??a.domain,display_name:a.display_name??a.name,bio:a.note??a.summary,avatar_url:a.avatar??a.avatar_url})).filter((a:any)=>a.username))}catch{setFediverse([])}}
  }catch(e){toast.error(e instanceof CapabilityClientError&&e.code==='RATE_LIMITED'?'Search is rate limited briefly. Try again in a moment.':'Search could not be completed')}finally{setLoading(false);setLoadingMore(false)}};
 useEffect(()=>{if(initial)run(initial,tab)},[initial]);
 useEffect(()=>{const node=sentinel.current;if(!node||!hasMore)return;const io=new IntersectionObserver(es=>{if(es[0]?.isIntersecting&&!loading&&!loadingMore&&data.next_cursor)run(query,tab,true)},{rootMargin:'700px'});io.observe(node);return()=>io.disconnect()},[data.next_cursor,loading,loadingMore,query,tab]);
 const choose=(value:string,nextTab='Top')=>{setQuery(value);setShowSuggest(false);setTab(nextTab);run(value,nextTab)};
 const posts=useMemo(()=>{let rows=[...data.posts];if(mediaOnly)rows=rows.filter((p:any)=>p.media_url||p.media_type||p.is_video||p.image_url||p.video_url);if(tab==='Latest'||sort==='Latest')rows.sort((a:any,b:any)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime());if(sort==='Most liked')rows.sort((a:any,b:any)=>(b.likes_count??0)-(a.likes_count??0));if(sort==='Most viewed')rows.sort((a:any,b:any)=>(b.views_count??0)-(a.views_count??0));return rows},[data.posts,tab,sort,mediaOnly]);
 const clear=()=>{setQuery('');setShowSuggest(true);setData({users:[],hashtags:[],posts:[],communities:[],next_cursor:null});setFediverse([])};
 return <div className="min-h-screen bg-background pb-16 md:pb-0"><TopBar title="Search" showBack/><div ref={box} className="sticky top-14 z-40 bg-background/95 backdrop-blur border-b border-border"><form onSubmit={e=>{e.preventDefault();run(query)}} className="px-3 pt-3 pb-2"><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground"/><Input value={query} onChange={e=>{const v=e.target.value;setQuery(v);setShowSuggest(true);if(inputTimer.current)clearTimeout(inputTimer.current);inputTimer.current=setTimeout(()=>suggestFor(v),160)}} onFocus={()=>{setShowSuggest(true);if(query)suggestFor(query)}} placeholder="Search Testagram" className="h-12 pl-12 pr-20 rounded-full bg-muted/80 border-transparent focus-visible:ring-1 focus-visible:ring-primary"/>{query&&<button type="button" onClick={clear} className="absolute right-3 top-1/2 -translate-y-1/2 p-2 rounded-full hover:bg-background"><X className="w-4 h-4"/></button>}</div></form>
 {showSuggest&&<div className="absolute left-3 right-3 top-[68px] bg-background border border-border rounded-2xl shadow-2xl overflow-hidden max-h-[70vh] overflow-y-auto">{suggestLoading&&<div className="px-4 py-3 flex gap-2 text-xs text-muted-foreground"><Loader2 className="w-4 h-4 animate-spin"/>Finding suggestions…</div>}{!query&&recent.length>0&&<section className="py-2"><div className="px-4 py-2 flex justify-between text-[11px] font-bold uppercase tracking-widest text-muted-foreground">Recent searches<button className="text-primary normal-case tracking-normal" onClick={()=>{setRecent([]);localStorage.removeItem('tsocial_recent_searches')}}>Clear</button></div>{recent.map(r=><button key={r} onClick={()=>choose(r)} className="w-full px-4 py-2.5 flex items-center gap-3 hover:bg-muted text-left"><Clock3 className="w-4 h-4 text-muted-foreground"/><span className="truncate">{r}</span></button>)}</section>}
 {suggest.users.length>0&&<section className="py-2 border-t border-border"><div className="px-4 py-2 text-[11px] font-bold uppercase tracking-widest text-muted-foreground">People</div>{suggest.users.slice(0,5).map((p:any)=><button key={p.id} onClick={()=>choose(`@${p.username}`,'People')} className="w-full px-4 py-2.5 flex items-center gap-3 hover:bg-muted text-left"><div className="w-9 h-9 rounded-full bg-muted overflow-hidden">{p.avatar_url?<img src={p.avatar_url} alt="" className="w-full h-full object-cover"/>:<div className="w-full h-full grid place-items-center font-bold">{p.username?.[0]?.toUpperCase()}</div>}</div><div className="min-w-0 flex-1"><div className="font-semibold flex items-center gap-1">@{p.username}{p.verified&&<VerifiedTick className="w-3.5 h-3.5 text-primary"/>}{p.is_protected&&<Lock className="w-3 h-3 text-muted-foreground" aria-label="Protected account"/>}</div><div className="text-xs text-muted-foreground truncate">{p.display_name||p.bio}</div><div className="text-[11px] text-muted-foreground mt-0.5">{formatNumber(p.followers_count??0)} followers</div></div><AtSign className="w-4 h-4 text-muted-foreground"/></button>)}</section>}
 {suggest.hashtags.length>0&&<section className="py-2 border-t border-border"><div className="px-4 py-2 text-[11px] font-bold uppercase tracking-widest text-muted-foreground">Topics</div>{suggest.hashtags.slice(0,6).map((h:any)=><button key={h.id} onClick={()=>choose(`#${h.tag}`,'Hashtags')} className="w-full px-4 py-2.5 flex items-center gap-3 hover:bg-muted text-left"><span className="w-8 h-8 rounded-full bg-primary/10 grid place-items-center"><Hash className="w-4 h-4 text-primary"/></span><span className="flex-1"><b>#{h.tag}</b><span className="block text-xs text-muted-foreground">{formatNumber(h.usage_count??0)} posts</span></span><TrendingUp className="w-4 h-4 text-muted-foreground"/></button>)}</section>}
 {KEYWORDS.filter(k=>k.toLowerCase().includes(query.toLowerCase())).slice(0,5).map(k=><button key={k} onClick={()=>choose(k)} className="w-full px-4 py-3 flex items-center gap-3 border-t border-border hover:bg-muted text-left"><Sparkles className="w-4 h-4 text-primary"/><span>{k}</span></button>)}
 </div>}
 <div className="flex overflow-x-auto scrollbar-hide border-t border-border">{TABS.map(t=><button key={t} onClick={()=>{setTab(t);if(query)run(query,t)}} className={`shrink-0 px-4 py-3 text-sm font-semibold border-b-2 ${tab===t?'border-primary text-foreground':'border-transparent text-muted-foreground hover:text-foreground'}`}>{t}</button>)}</div>
 </div>
 <div className="px-3 py-2 border-b border-border flex items-center gap-2"><button onClick={()=>setShowFilters(v=>!v)} className="px-3 py-1.5 rounded-full border border-border text-xs font-semibold flex items-center gap-1.5"><ListFilter className="w-3.5 h-3.5"/>Filters<ChevronDown className={`w-3 h-3 transition-transform ${showFilters?'rotate-180':''}`}/></button>{sort!=='Relevance'&&<span className="text-xs text-muted-foreground">{sort}</span>}{mediaOnly&&<span className="text-xs text-muted-foreground">Media</span>}{verifiedOnly&&<span className="text-xs text-muted-foreground">Verified</span>}</div>
 {showFilters&&<div className="px-3 py-3 border-b border-border bg-muted/20 grid grid-cols-2 gap-2 text-sm"><button onClick={()=>setSort('Relevance')} className={`p-2 rounded-lg border ${sort==='Relevance'?'border-primary bg-primary/10':'border-border'}`}>Relevance</button><button onClick={()=>setSort('Latest')} className={`p-2 rounded-lg border ${sort==='Latest'?'border-primary bg-primary/10':'border-border'}`}>Latest</button><button onClick={()=>setSort('Most liked')} className={`p-2 rounded-lg border ${sort==='Most liked'?'border-primary bg-primary/10':'border-border'}`}>Most liked</button><button onClick={()=>setSort('Most viewed')} className={`p-2 rounded-lg border ${sort==='Most viewed'?'border-primary bg-primary/10':'border-border'}`}>Most viewed</button><button onClick={()=>setMediaOnly(v=>!v)} className={`p-2 rounded-lg border ${mediaOnly?'border-primary bg-primary/10':'border-border'}`}>Media only</button><button onClick={()=>setVerifiedOnly(v=>!v)} className={`p-2 rounded-lg border ${verifiedOnly?'border-primary bg-primary/10':'border-border'}`}>Verified</button></div>}
 {loading&&!data.posts.length?<div className="py-16 grid place-items-center text-muted-foreground"><Loader2 className="w-7 h-7 animate-spin"/></div>:!query?<div className="py-16 text-center px-8"><Search className="w-10 h-10 mx-auto mb-3 text-muted-foreground/50"/><h2 className="font-bold text-lg">Search Testagram</h2><p className="text-sm text-muted-foreground mt-1">Find people, posts, topics, communities and the Fediverse.</p></div>:tab==='People'?<ResultPeople items={data.users} navigate={navigate}/>:tab==='Hashtags'?<ResultHashtags items={data.hashtags} navigate={navigate}/>:tab==='Communities'?<ResultCommunities items={data.communities} navigate={navigate}/>:tab==='Fediverse'?<ResultFediverse items={fediverse}/>:<><GlobalSearchResults data={data} navigate={navigate}/><div>{posts.length?posts.map((p:any)=><PostCard key={p.id} post={p}/>):<div className="py-16 text-center text-sm text-muted-foreground">No matching posts yet.</div>}</div></>}
 <div ref={sentinel} className="py-8 flex justify-center">{loadingMore?<Loader2 className="w-5 h-5 animate-spin text-muted-foreground"/>:hasMore&&query&&tab!=='People'&&tab!=='Hashtags'&&tab!=='Communities'&&tab!=='Fediverse'?<span className="text-xs text-muted-foreground">Loading more as you scroll…</span>:query&&<span className="text-xs text-muted-foreground">End of results</span>}</div>
 </div>
}
function GlobalSearchResults({data,navigate}:{data:any;navigate:any}) {
 const groups=[
  ['People',data.users||[],(x:any)=>navigate('/profile/'+x.username)],
  ['Hashtags',data.hashtags||[],(x:any)=>navigate('/hashtag/'+x.tag)],
  ['Communities',data.communities||[],(x:any)=>navigate('/c/'+(x.slug||x.name))],
  ['Spaces',data.spaces||[],(x:any)=>navigate('/spaces/'+x.id)],
  ['Trending',data.trending||[],(x:any)=>navigate('/trending/'+encodeURIComponent(x.topic))]
 ];
 return <div>{groups.map(([name,items,go]:any)=>items.length>0&&<section key={name} className="border-b border-border">
  <div className="px-4 py-3 text-xs font-bold uppercase tracking-widest text-muted-foreground">{name}</div>
  {items.slice(0,8).map((x:any)=><button key={x.id} onClick={()=>go(x)} className="w-full px-4 py-3 text-left hover:bg-muted flex items-center gap-3">
   <div className="min-w-0 flex-1"><div className="font-semibold truncate">{x.display_name||x.username||('#'+x.tag)||x.title||x.topic}</div>
   <div className="text-xs text-muted-foreground truncate">{x.description||x.bio||x.category||''}</div></div>
  </button>)}
 </section>)}</div>;
}

function ResultPeople({items,navigate}:{items:any[];navigate:any}){return <div>{items.map(p=><button key={p.id} onClick={()=>navigate(`/profile/${p.username}`)} className="w-full px-4 py-3 flex items-center gap-3 border-b border-border hover:bg-muted text-left"><div className="w-11 h-11 rounded-full bg-muted overflow-hidden">{p.avatar_url?<img src={p.avatar_url} alt="" className="w-full h-full object-cover"/>:<div className="w-full h-full grid place-items-center font-bold">{p.username?.[0]?.toUpperCase()}</div>}</div><div className="min-w-0"><div className="font-bold flex gap-1 items-center">{p.display_name||p.username}{p.verified&&<VerifiedTick className="w-4 h-4 text-primary"/>}</div><div className="text-sm text-muted-foreground">@{p.username}{p.is_protected&&" · Protected"}</div><div className="text-xs text-muted-foreground truncate">{p.bio}</div><div className="text-[11px] text-muted-foreground mt-0.5">{formatNumber(p.followers_count??0)} followers</div></div></button>)}</div>}
function ResultHashtags({items,navigate}:{items:any[];navigate:any}){return <div>{items.map(h=><button key={h.id} onClick={()=>navigate(`/hashtag/${h.tag}`)} className="w-full px-4 py-4 border-b border-border text-left hover:bg-muted"><div className="font-bold text-lg">#{h.tag}</div><div className="text-xs text-muted-foreground">{formatNumber(h.usage_count??0)} posts</div></button>)}</div>}
function ResultCommunities({items,navigate}:{items:any[];navigate:any}){return <div>{items.map(c=><button key={c.id} onClick={()=>navigate(`/c/${c.slug||c.name}`)} className="w-full px-4 py-4 border-b border-border text-left hover:bg-muted"><div className="font-bold">{c.display_name||c.name}</div><div className="text-xs text-muted-foreground">{formatNumber(c.member_count??0)} members · {formatNumber(c.post_count??0)} posts</div><p className="text-sm text-muted-foreground mt-1 line-clamp-2">{c.description}</p></button>)}</div>}
function ResultFediverse({items}:{items:any[]}){return <div>{items.map((a:any,i)=><div key={a.actor_url||i} className="px-4 py-3 border-b border-border flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-muted overflow-hidden">{a.avatar_url&&<img src={a.avatar_url} alt="" className="w-full h-full object-cover"/>}</div><div className="min-w-0"><div className="font-semibold">{a.display_name||a.username}</div><div className="text-sm text-muted-foreground">@{a.username}{a.domain?`@${a.domain}`:''}</div><div className="text-xs text-muted-foreground line-clamp-2">{a.bio}</div></div><Globe2 className="w-4 h-4 ml-auto text-muted-foreground"/></div>)}</div>}
