import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/hooks/useAuth';
import { TopBar } from '@/components/layout/TopBar';
import { Search, ShoppingBag, ShoppingCart, Heart, Home, Store, Package, Loader2, ArrowRight, Sparkles } from 'lucide-react';
import { toast } from 'sonner';

type Product={id:string;seller_id:string;name:string;description:string|null;price_minor:number;currency:string;inventory_count:number;category:string;region:string;is_featured:boolean;media_asset_id:string|null;created_at:string;image?:string;username?:string};

const CATS=[['all','All'],['fashion','Fashion'],['electronics','Electronics'],['handmade','Handmade'],['art','Art'],['home','Home'],['books','Books'],['food','Food'],['other','Other']];

export default function ShoppingMallPage(){
 const {user}=useAuth();const navigate=useNavigate();const [products,setProducts]=useState<Product[]>([]);const [q,setQ]=useState('');const [cat,setCat]=useState('all');const [loading,setLoading]=useState(true);const [cart,setCart]=useState<Record<string,number>>({});
 const load=async()=>{setLoading(true);let query=supabase.from('products').select('id,seller_id,name,description,price_minor,currency,inventory_count,category,region,is_featured,media_asset_id,created_at').eq('status','active').order('is_featured',{ascending:false}).order('created_at',{ascending:false}).limit(60);if(cat!=='all')query=query.eq('category',cat);const {data,error}=await query;if(error){toast.error(error.message);setProducts([]);setLoading(false);return}const rows=data??[];const ids=rows.map(x=>x.media_asset_id).filter(Boolean) as string[];const sellers=[...new Set(rows.map(x=>x.seller_id))];const [{data:media},{data:profiles}]=await Promise.all([ids.length?supabase.from('media_assets').select('id,media_url').in('id',ids):Promise.resolve({data:[] as any[]}),sellers.length?supabase.from('profiles').select('id,username').in('id',sellers):Promise.resolve({data:[] as any[]})]);const mm=new Map((media??[]).map(x=>[x.id,x.media_url]));const pp=new Map((profiles??[]).map(x=>[x.id,x.username]));setProducts(rows.map(x=>({...x,image:x.media_asset_id?mm.get(x.media_asset_id):undefined,username:pp.get(x.seller_id)})));setLoading(false)};
 useEffect(()=>{load()},[cat]); // eslint-disable-line react-hooks/exhaustive-deps
 const shown=useMemo(()=>products.filter(p=>!q.trim()||p.name.toLowerCase().includes(q.toLowerCase())||p.description?.toLowerCase().includes(q.toLowerCase())),[products,q]);
 const buy=async(p:Product)=>{if(!user){toast.error('Sign in to shop');return}const qty=cart[p.id]??1;const {error}=await supabase.rpc('place_marketplace_order',{p_product_id:p.id,p_quantity:qty});if(error)toast.error(error.message);else{toast.success('Order placed');setCart(c=>({...c,[p.id]:1}));load()}};
 return <div className="min-h-screen bg-background pb-16 lg:pb-0"><TopBar title="Shopping Mall"/><div className="p-4 space-y-5">
  <div className="flex items-center justify-between gap-3"><button onClick={()=>navigate('/')} className="flex items-center gap-2 font-bold"><Home className="w-4 h-4"/>Home</button><div className="flex gap-2"><button onClick={()=>navigate('/wishlist')} className="p-2 rounded-xl border border-border hover:bg-muted"><Heart className="w-4 h-4"/></button><button onClick={()=>navigate('/orders')} className="p-2 rounded-xl border border-border hover:bg-muted"><Package className="w-4 h-4"/></button></div></div>
  <section className="rounded-3xl bg-gradient-to-br from-primary/15 via-background to-muted border border-primary/20 p-5"><div className="flex items-center gap-2 text-primary text-xs font-black uppercase tracking-widest"><Store className="w-4 h-4"/>Testagram Mall</div><h1 className="text-3xl font-black mt-2">Shop the community.</h1><p className="text-sm text-muted-foreground mt-1">Discover products from creators and sellers across Testagram.</p><div className="mt-4 flex gap-2"><button onClick={()=>navigate('/products')} className="px-4 py-2 rounded-xl bg-primary text-primary-foreground text-sm font-bold">Sell a product</button><button onClick={()=>navigate('/')} className="px-4 py-2 rounded-xl border border-border text-sm font-bold">Back home</button></div></section>
  <div className="flex gap-2 overflow-x-auto pb-1">{CATS.map(([id,label])=><button key={id} onClick={()=>setCat(id)} className={`px-3 py-1.5 rounded-full text-xs font-bold whitespace-nowrap border ${cat===id?'bg-primary text-primary-foreground border-primary':'border-border hover:bg-muted'}`}>{label}</button>)}</div>
  <div className="relative"><Search className="absolute left-3 top-3 w-4 h-4 text-muted-foreground"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search the mall…" className="w-full pl-9 pr-3 py-2.5 rounded-xl border border-border bg-background text-sm"/></div>
  {loading?<div className="py-16 flex justify-center"><Loader2 className="w-6 h-6 animate-spin"/></div>:shown.length?<div className="grid grid-cols-2 gap-3">{shown.map(p=><article key={p.id} className="rounded-2xl border border-border bg-card overflow-hidden">{p.image?<img src={p.image} alt="" className="w-full aspect-square object-cover"/>:<div className="w-full aspect-square bg-muted flex items-center justify-center"><ShoppingBag className="w-10 h-10 text-muted-foreground/30"/></div>}<div className="p-3 space-y-2"><div className="flex items-start justify-between gap-2"><h2 className="font-bold text-sm line-clamp-2">{p.name}</h2>{p.is_featured&&<Sparkles className="w-3.5 h-3.5 text-primary shrink-0"/>}</div><p className="text-lg font-black text-primary">{p.currency} {(p.price_minor/100).toFixed(2)}</p><p className="text-[10px] text-muted-foreground">by @{p.username??'seller'} · {p.inventory_count} left</p><div className="flex items-center gap-2"><button disabled={p.inventory_count<1} onClick={()=>setCart(c=>({...c,[p.id]:Math.min(p.inventory_count,(c[p.id]??1)+1)}))} className="px-2 py-1 rounded-lg border border-border text-xs">+</button><span className="text-xs font-bold">{cart[p.id]??1}</span><button disabled={(cart[p.id]??1)<=1} onClick={()=>setCart(c=>({...c,[p.id]:Math.max(1,(c[p.id]??1)-1)}))} className="px-2 py-1 rounded-lg border border-border text-xs">−</button><button onClick={()=>buy(p)} className="ml-auto px-3 py-1.5 rounded-xl bg-primary text-primary-foreground text-xs font-bold flex items-center gap-1"><ShoppingCart className="w-3.5 h-3.5"/>Buy</button></div></div></article>)}</div>:<div className="text-center py-16 text-muted-foreground">No products match this search.</div>}
 </div></div>
}
