import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Bookmark, Check, Heart, Loader2, MessageCircle, MoreHorizontal, Repeat2, Quote, Share2, Trash2 } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import { TopBar } from '@/components/layout/TopBar';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/lib/supabase';
import { formatNumber } from '@/lib/utils';
import { useSEO } from '@/hooks/useSEO';
import { toast } from 'sonner';

type Profile={id:string;username:string;avatar_url:string|null;verified:boolean;display_name?:string|null};
type Thread={id:string;owner_id:string;title?:string|null;body:string;visibility:string;created_at:string;likes_count:number;reposts_count:number;quotes_count:number;replies_count:number;views_count:number;media_urls:string[];profiles?:Profile};
type Reply={id:string;thread_id:string;user_id:string;content:string;created_at:string;parent_reply_id:string|null;profiles?:Profile};

function Avatar({profile}:{profile?:Profile}){return <div className="h-10 w-10 shrink-0 overflow-hidden rounded-full bg-muted flex items-center justify-center font-bold">{profile?.avatar_url?<img src={profile.avatar_url} alt="" className="h-full w-full object-cover"/>:(profile?.username||'?').slice(0,1).toUpperCase()}</div>}

export default function ThreadDetailPage(){
 const {id}=useParams(); const {user}=useAuth(); const navigate=useNavigate();
 const [thread,setThread]=useState<Thread|null>(null); const [replies,setReplies]=useState<Reply[]>([]); const [loading,setLoading]=useState(true);
 const [liked,setLiked]=useState(false); const [reposted,setReposted]=useState(false); const [bookmarked,setBookmarked]=useState(false);
 const [replyText,setReplyText]=useState(''); const [quoteText,setQuoteText]=useState(''); const [quoting,setQuoting]=useState(false); const [sending,setSending]=useState(false);
 useSEO({title:thread?.body?.slice(0,60)||'Thread',description:thread?.body?.slice(0,155)||'Join the conversation on Testagram',url:id?'/thread/'+id:undefined,type:'article'});

 const load=useCallback(async()=>{
  if(!id)return; setLoading(true);
  try{
   const {data,error}=await supabase.from('threads').select('id, owner_id, title, body, visibility, created_at, likes_count, reposts_count, quotes_count, replies_count, views_count, media_urls').eq('id',id).is('deleted_at',null).single();
   if(error)throw error;
   const t=data as Thread; const profile=(await supabase.from('profiles').select('id, username, avatar_url, verified, display_name').eq('id',t.owner_id).maybeSingle()).data as Profile|null;
   t.profiles=profile??undefined; t.media_urls=Array.isArray(t.media_urls)?t.media_urls:[]; setThread(t);
   const {data:replyRows}=await supabase.from('thread_replies').select('id, thread_id, user_id, content, created_at, parent_reply_id').eq('thread_id',id).order('created_at',{ascending:true}).limit(200);
   const rs=(replyRows??[]) as Reply[]; const uids=[...new Set(rs.map(r=>r.user_id))]; const ps=uids.length?(await supabase.from('profiles').select('id, username, avatar_url, verified, display_name').in('id',uids)).data??:[]; const pm=new Map(ps.map((p:any)=>[p.id,p])); setReplies(rs.map(r=>({...r,profiles:pm.get(r.user_id)})));
   if(user){const [l,r,b]=await Promise.all([supabase.from('thread_likes').select('id').eq('thread_id',id).eq('user_id',user.id).maybeSingle(),supabase.from('thread_reposts').select('id').eq('thread_id',id).eq('user_id',user.id).maybeSingle(),supabase.from('thread_bookmarks').select('id').eq('thread_id',id).eq('user_id',user.id).maybeSingle()]);setLiked(!!l.data);setReposted(!!r.data);setBookmarked(!!b.data);}
   const key='ts-thread-view-'+id; if(!sessionStorage.getItem(key)&&user){const {data:viewCount}=await supabase.rpc('testagram_record_thread_view',{p_thread_id:id});if(typeof viewCount==='number')setThread(prev=>prev?{...prev,views_count:viewCount}:prev);sessionStorage.setItem(key,'1');}
  }catch(error){console.error('Thread detail error',error);toast.error('Thread not found');navigate('/threads');}finally{setLoading(false)}
 },[id,user?.id,navigate]);
 useEffect(()=>{void load()},[load]);
 const requireAuth=()=>{if(!user){navigate('/auth');return false}return true};
 const like=async()=>{if(!requireAuth()||!thread)return;const active=!liked;setLiked(active);setThread(t=>t?{...t,likes_count:Math.max(0,t.likes_count+(active?1:-1))}:t);const res=active?await supabase.from('thread_likes').insert({thread_id:thread.id,user_id:user!.id}):await supabase.from('thread_likes').delete().eq('thread_id',thread.id).eq('user_id',user!.id);if(res.error){setLiked(!active);setThread(t=>t?{...t,likes_count:Math.max(0,t.likes_count+(active?-1:1))}:t);toast.error('Like failed')}};
 const repost=async()=>{if(!requireAuth()||!thread)return;const active=!reposted;setReposted(active);setThread(t=>t?{...t,reposts_count:Math.max(0,t.reposts_count+(active?1:-1))}:t);const res=active?await supabase.from('thread_reposts').insert({thread_id:thread.id,user_id:user!.id}):await supabase.from('thread_reposts').delete().eq('thread_id',thread.id).eq('user_id',user!.id);if(res.error){setReposted(!active);setThread(t=>t?{...t,reposts_count:Math.max(0,t.reposts_count+(active?-1:1))}:t);toast.error('Repost failed')}};
 const bookmark=async()=>{if(!requireAuth()||!thread)return;const active=!bookmarked;setBookmarked(active);const res=active?await supabase.from('thread_bookmarks').insert({thread_id:thread.id,user_id:user!.id}):await supabase.from('thread_bookmarks').delete().eq('thread_id',thread.id).eq('user_id',user!.id);if(res.error){setBookmarked(!active);toast.error('Bookmark failed')}else toast.success(active?'Saved':'Removed from saved')};
 const reply=async()=>{if(!requireAuth()||!thread||!replyText.trim())return;setSending(true);const {error}=await supabase.from('thread_replies').insert({thread_id:thread.id,user_id:user!.id,content:replyText.trim(),parent_reply_id:null});if(error)toast.error('Reply failed');else{setReplyText('');setThread(t=>t?{...t,replies_count:t.replies_count+1}:t);toast.success('Reply posted');await load()}setSending(false)};
 const quote=async()=>{if(!requireAuth()||!thread||!quoteText.trim())return;setSending(true);const {error}=await supabase.from('thread_quotes').insert({thread_id:thread.id,user_id:user!.id,content:quoteText.trim()});if(error)toast.error('Quote failed');else{setQuoteText('');setQuoting(false);setThread(t=>t?{...t,quotes_count:t.quotes_count+1}:t);toast.success('Quote posted')}setSending(false)};
 const remove=async()=>{if(!thread||!user||thread.owner_id!==user.id)return;if(!window.confirm('Delete this thread?'))return;const {error}=await supabase.from('threads').update({deleted_at:new Date().toISOString()}).eq('id',thread.id).eq('owner_id',user.id);if(error)toast.error('Could not delete thread');else{toast.success('Thread deleted');navigate('/threads')}};
 if(loading)return <div className="min-h-screen bg-background"><TopBar title="Thread" showBack/><div className="flex justify-center py-24"><Loader2 className="h-7 w-7 animate-spin text-primary"/></div></div>;
 if(!thread)return null; const profile=thread.profiles;
 return <div className="min-h-screen bg-background pb-20 md:pb-0"><TopBar title="Thread" showBack/><main>
  <article className="px-4 py-5"><div className="flex gap-3"><button onClick={()=>navigate('/profile/'+(profile?.username||''))}><Avatar profile={profile}/></button><div className="min-w-0 flex-1">
   <div className="flex items-start gap-2"><div><p className="font-bold">{profile?.display_name||profile?.username||'Testagram user'} {profile?.verified&&<Check className="inline h-4 w-4 rounded-full bg-primary p-0.5 text-primary-foreground"/>}</p><p className="text-xs text-muted-foreground">@{profile?.username||'user'} · {formatDistanceToNow(new Date(thread.created_at),{addSuffix:true})}</p></div><button className="ml-auto rounded-full p-2 hover:bg-muted"><MoreHorizontal className="h-4 w-4"/></button></div>
   {thread.title&&<h1 className="mt-4 text-xl font-bold">{thread.title}</h1>}<p className="mt-3 whitespace-pre-wrap break-words text-[16px] leading-7">{thread.body}</p>
   {thread.media_urls.length>0&&<div className={'mt-4 grid gap-2 overflow-hidden rounded-2xl border border-border '+(thread.media_urls.length>1?'grid-cols-2':'grid-cols-1')}>{thread.media_urls.slice(0,4).map(url=><img key={url} src={url} alt="" className="max-h-[560px] w-full object-cover"/>)}</div>}
   <div className="mt-5 flex items-center justify-between border-b border-border pb-4 text-muted-foreground"><button onClick={()=>setReplyText(v=>v?'':' ')} className="flex items-center gap-1.5 rounded-full p-2 hover:text-primary"><MessageCircle className="h-5 w-5"/>{thread.replies_count>0&&<span className="text-xs">{formatNumber(thread.replies_count)}</span>}</button><button onClick={repost} className={'flex items-center gap-1.5 rounded-full p-2 '+(reposted?'text-green-600':'hover:text-green-600')}><Repeat2 className="h-5 w-5"/>{thread.reposts_count>0&&<span className="text-xs">{formatNumber(thread.reposts_count)}</span>}</button><button onClick={like} className={'flex items-center gap-1.5 rounded-full p-2 '+(liked?'text-pink-600':'hover:text-pink-600')}><Heart className={'h-5 w-5 '+(liked?'fill-current':'')}/>{thread.likes_count>0&&<span className="text-xs">{formatNumber(thread.likes_count)}</span>}</button><button onClick={()=>setQuoting(v=>!v)} className="flex items-center gap-1.5 rounded-full p-2 hover:text-primary"><Quote className="h-5 w-5"/>{thread.quotes_count>0&&<span className="text-xs">{formatNumber(thread.quotes_count)}</span>}</button><button onClick={bookmark} className={'rounded-full p-2 '+(bookmarked?'text-primary':'hover:text-primary')}><Bookmark className={'h-5 w-5 '+(bookmarked?'fill-current':'')}/></button><button onClick={()=>navigator.share?.({title:'Testagram thread',text:thread.body,url:window.location.href})} className="rounded-full p-2 hover:text-primary"><Share2 className="h-5 w-5"/></button>{user?.id===thread.owner_id&&<button onClick={()=>void remove()} className="rounded-full p-2 hover:text-destructive"><Trash2 className="h-5 w-5"/></button>}</div>
   <p className="pt-3 text-xs text-muted-foreground">{formatNumber(thread.views_count)} views</p>
  </div></div></article>
  {replyText!==''&&<div className="border-y border-border bg-muted/20 p-4"><div className="flex gap-3"><Avatar profile={{id:user?.id||'',username:user?.username||'you',avatar_url:user?.avatar||null,verified:false}}/><div className="flex-1"><Textarea autoFocus value={replyText.trim()} onChange={e=>setReplyText(e.target.value)} placeholder="Reply to this thread…" className="min-h-24 resize-none"/><div className="mt-3 flex justify-end gap-2"><Button variant="ghost" onClick={()=>setReplyText('')}>Cancel</Button><Button onClick={()=>void reply()} disabled={sending||!replyText.trim()} className="rounded-full">{sending?<Loader2 className="h-4 w-4 animate-spin"/>:'Reply'}</Button></div></div></div></div>}
  {quoting&&<div className="border-b border-border bg-muted/20 p-4"><div className="flex gap-3"><Avatar profile={{id:user?.id||'',username:user?.username||'you',avatar_url:user?.avatar||null,verified:false}}/><div className="flex-1"><div className="rounded-2xl border border-border bg-background p-3 text-sm text-muted-foreground">“{thread.body.slice(0,220)}{thread.body.length>220?'…':''}”</div><Textarea autoFocus value={quoteText} onChange={e=>setQuoteText(e.target.value.slice(0,500))} placeholder="Add your thought…" className="mt-3 min-h-20 resize-none"/><div className="mt-2 flex justify-end gap-2"><Button variant="ghost" onClick={()=>setQuoting(false)}>Cancel</Button><Button onClick={()=>void quote()} disabled={sending||!quoteText.trim()} className="rounded-full">Quote</Button></div></div></div></div>}
  <section className="divide-y divide-border"><div className="px-4 py-3 text-sm font-bold">Replies</div>{replies.length===0?<div className="px-6 py-12 text-center text-sm text-muted-foreground">No replies yet. Start the conversation.</div>:replies.map(r=><article key={r.id} className="px-4 py-4"><div className="flex gap-3"><Avatar profile={r.profiles}/><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="font-semibold text-sm">{r.profiles?.display_name||r.profiles?.username||'User'}</span>{r.profiles?.verified&&<Check className="h-3.5 w-3.5 rounded-full bg-primary p-0.5 text-primary-foreground"/>}<span className="text-xs text-muted-foreground">· {formatDistanceToNow(new Date(r.created_at),{addSuffix:true})}</span></div><p className="mt-1 whitespace-pre-wrap text-sm leading-6">{r.content}</p></div></div></article>)}</section>
 </main></div>;