import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Copy, ExternalLink, Link2, Mic, MicOff, Radio, RefreshCw, ShieldBan, ShieldCheck, Users, Video } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useNavigate, useParams } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/hooks/useAuth';
import { toast } from 'sonner';
import { TestagramTvMediaSession } from '@/lib/testagramTvMedia';

type Guest={id:string;slot:number;label:string;status:string;expires_at:string;claimed_by:string|null;muted:boolean;blocked:boolean};
const api=async(body:Record<string,unknown>)=>{const {data}=await supabase.auth.getSession();const r=await fetch('/api/live',{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json',...(data.session?.access_token?{Authorization:'Bearer '+data.session.access_token}:{})},body:JSON.stringify(body)});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error?.message||'Guest control request failed.');return p?.data;};

export default function TvGuestControlPage(){
 const {streamId}=useParams();const nav=useNavigate();const {user}=useAuth();const bridgeRef=useRef<TestagramTvMediaSession|null>(null);
 const [slots,setSlots]=useState<Guest[]>([]);const [capacity,setCapacity]=useState(6);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<number|null>(null);const [bridgeReady,setBridgeReady]=useState(false);
 const load=useCallback(async()=>{if(!streamId)return;setLoading(true);try{const d=await api({action:'guest-control-list',stream_id:streamId});setCapacity(Number(d?.capacity||6));setSlots(Array.isArray(d?.slots)?d.slots:[]);}catch(e:any){toast.error(e?.message||'Could not load guest slots.');}finally{setLoading(false);}},[streamId]);
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(),4000);return()=>window.clearInterval(id);},[load]);
 useEffect(()=>{let dead=false;(async()=>{if(!streamId||!user)return;try{await api({action:'viewer',stream_id:streamId});const s=await TestagramTvMediaSession.connectHostGuestBridge(streamId,new MediaStream());if(dead){await s.close();return;}bridgeRef.current=s;setBridgeReady(true);}catch{setBridgeReady(false);}})();return()=>{dead=true;void bridgeRef.current?.close();bridgeRef.current=null;setBridgeReady(false);};},[streamId,user]);
 const invite=async()=>{try{const d=await api({action:'create-guest',stream_id:streamId});const url=window.location.origin+'/tv/live/'+streamId+'?guest='+encodeURIComponent(String(d.invite_token));await navigator.clipboard.writeText(url).catch(()=>undefined);await load();toast.success('Guest '+d.guest_slot+' link copied.');}catch(e:any){toast.error(e?.message||'Could not create guest link.');}};
 const control=async(g:Guest,c:'mute'|'unmute'|'block'|'unblock')=>{setBusy(g.slot);try{await api({action:'guest-control',stream_id:streamId,guest_slot:g.slot,control:c});if(bridgeRef.current)await bridgeRef.current.sendGuestControl(g.slot,c);await load();toast.success(g.label+' '+c+'.');}catch(e:any){toast.error(e?.message||'Guest control failed.');}finally{setBusy(null);}};
 const copy=async(g:Guest)=>{toast.info('Invite links are single-use and are not retained server-side. Generate a replacement when a slot is free.');};
 const share=async(g:Guest)=>{void g;await copy(g);};
 const sorted=useMemo(()=>[...slots].sort((a,b)=>a.slot-b.slot),[slots]);
 return <div className="min-h-screen bg-black text-white"><header className="sticky top-0 z-20 border-b border-white/10 bg-zinc-950/95 px-4 py-3"><div className="mx-auto max-w-6xl flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Button size="sm" variant="outline" onClick={()=>nav(streamId?'/tv-studio/'+streamId:'/tv-studio')}><ArrowLeft className="w-4 h-4"/></Button><div><h1 className="font-bold flex items-center gap-2"><Users className="w-5 h-5"/>Guest Control Room</h1><p className="text-xs text-zinc-500">All guest slots · media controls · invitation capacity</p></div></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>void load()}><RefreshCw className="w-4 h-4 mr-1"/>Refresh</Button><Button size="sm" onClick={()=>void invite()} disabled={slots.length>=capacity}><Link2 className="w-4 h-4 mr-1"/>Generate Guest link</Button></div></div></header>
 <main className="mx-auto max-w-6xl p-4 space-y-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Capacity',capacity],['Allocated',slots.length],['Connected',slots.filter(g=>g.status==='connected').length],['Bridge',bridgeReady?'READY':'OFFLINE']].map(([a,b])=><div key={String(a)} className="rounded-xl border border-white/10 bg-zinc-900 p-3"><div className="text-xs text-zinc-500">{a}</div><div className="text-2xl font-bold">{b}</div></div>)}</div>
 <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{Array.from({length:capacity},(_,i)=>i+1).map(n=>{const g=sorted.find(x=>x.slot===n);return <article key={n} className={'rounded-2xl border p-3 '+(g?.blocked?'border-red-500/40 bg-red-950/20':'border-white/10 bg-zinc-900')}><div className="aspect-video rounded-xl bg-black border border-white/10 flex items-center justify-center relative"><span className="text-sm text-zinc-600">{g?.status==='connected'?'MEDIA CONNECTED':'Guest '+n+(g?' · INVITED':' · EMPTY')}</span><span className="absolute top-2 left-2 bg-black/70 rounded px-2 py-1 text-[10px] font-bold">GUEST {n}</span><span className="absolute top-2 right-2 bg-zinc-800 rounded px-2 py-1 text-[10px] font-bold">{g?.blocked?'BLOCKED':g?.status?.toUpperCase()||'EMPTY'}</span></div>
 <div className="mt-3 flex justify-between"><div><div className="font-semibold">Guest {n}</div><div className="text-[10px] text-zinc-500">{g?.claimed_by?'Claimed':'Waiting'}</div></div><Radio className={'w-4 h-4 '+(g?.status==='connected'?'text-emerald-400':'text-zinc-600')}/></div>
 {g?<div className="mt-3 grid grid-cols-2 gap-2"><Button size="sm" variant={g.muted?'destructive':'outline'} disabled={busy===n||g.blocked} onClick={()=>void control(g,g.muted?'unmute':'mute')}>{g.muted?<MicOff className="w-4 h-4 mr-1"/>:<Mic className="w-4 h-4 mr-1"/>}{g.muted?'Unmute':'Mute'}</Button><Button size="sm" variant={g.blocked?'default':'destructive'} disabled={busy===n} onClick={()=>void control(g,g.blocked?'unblock':'block')}>{g.blocked?<ShieldCheck className="w-4 h-4 mr-1"/>:<ShieldBan className="w-4 h-4 mr-1"/>}{g.blocked?'Unblock':'Block'}</Button><Button size="sm" variant="outline" onClick={()=>void copy(g)}><Copy className="w-4 h-4 mr-1"/>Copy</Button><Button size="sm" variant="outline" onClick={()=>void share(g)}><ExternalLink className="w-4 h-4 mr-1"/>Share</Button></div>:<Button className="w-full mt-3" size="sm" variant="outline" disabled={slots.length>=capacity} onClick={()=>void invite()}><Link2 className="w-4 h-4 mr-1"/>Generate Guest {n} link</Button>}
 {g&&<div className="mt-2 text-[10px] text-zinc-500">Expires {new Date(g.expires_at).toLocaleTimeString()} · {g.muted?'MIC MUTED · ':''}{g.blocked?'SLOT BLOCKED':''}</div>}</article>})}</div>
 <div className="rounded-2xl border border-white/10 bg-zinc-900 p-4 text-xs text-zinc-500"><b className="text-white">Forensic controls:</b> slot identity is server allocated 1–6; mute/block state is stored server-side and broadcast to the matching guest; each guest slot is independent; invitations remain single-use.</div></main></div>;
}
