name = "testagram-heartbeat"
account_id = "77dbe7a859196105dc84fbb6b7094019"
main = "src/index.ts"
compatibility_date = "2026-09-19"
workers_dev = false

[vars]
SUPABASE_HEARTBEAT_RPC_URL = "https://ffrhglgkukgsuhxenena.supabase.co/rest/v1/rpc/touch_user_heartbeat"
SUPABASE_PUBLISHABLE_KEY = "sb_publishable_h51Z3EHP2LN5o7HdRAB3Og_uhUA3oya"

[observability]
enabled = true

[[routes]]
pattern = "heartbeat.testagram.site"
custom_domain = true
