name = "testagram-heartbeat"
account_id = "77dbe7a859196105dc84fbb6b7094019"
main = "src/index.ts"
compatibility_date = "2026-09-19"
workers_dev = false

[vars]
SUPABASE_HEARTBEAT_URL = "https://ffrhglgkukgsuhxenena.supabase.co/functions/v1/heartbeat"

[observability]
enabled = true

[[routes]]
pattern = "heartbeat.testagram.site"
custom_domain = true
