-- Testagram communication plane: native identity/data, Matrix bridge downstream, LiveKit media downstream.
create table if not exists public.call_sessions (id uuid primary key default gen_random_uuid(),conversation_id uuid not null references public.conversations(id) on delete cascade,created_by uuid not null references public.profiles(id) on delete cascade,provider text not null default 'livekit' check(provider in('livekit','matrixrtc')),room_name text not null unique,kind text not null default 'video' check(kind in('voice','video','screen')),status text not null default 'ringing' check(status in('ringing','active','ended','failed')),started_at timestamptz,ended_at timestamptz,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.call_participants (call_id uuid not null references public.call_sessions(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,joined_at timestamptz,left_at timestamptz,primary key(call_id,user_id));
alter table public.call_sessions enable row level security; alter table public.call_participants enable row level security;
drop policy if exists call_sessions_member_read on public.call_sessions; create policy call_sessions_member_read on public.call_sessions for select to authenticated using(exists(select 1 from public.conversation_members cm where cm.conversation_id=call_sessions.conversation_id and cm.user_id=auth.uid()));
drop policy if exists call_sessions_member_write on public.call_sessions; create policy call_sessions_member_write on public.call_sessions for all to authenticated using(created_by=auth.uid() or exists(select 1 from public.conversation_members cm where cm.conversation_id=call_sessions.conversation_id and cm.user_id=auth.uid())) with check(created_by=auth.uid() or exists(select 1 from public.conversation_members cm where cm.conversation_id=call_sessions.conversation_id and cm.user_id=auth.uid()));
drop policy if exists call_participants_member_read on public.call_participants; create policy call_participants_member_read on public.call_participants for select to authenticated using(exists(select 1 from public.call_sessions cs join public.conversation_members cm on cm.conversation_id=cs.conversation_id where cs.id=call_participants.call_id and cm.user_id=auth.uid()));
drop policy if exists call_participants_self_write on public.call_participants; create policy call_participants_self_write on public.call_participants for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant select,insert,update on public.call_sessions to authenticated; grant select,insert,update on public.call_participants to authenticated;
create index if not exists call_sessions_conversation_created_idx on public.call_sessions(conversation_id,created_at desc);
create table if not exists public.communication_delivery_outbox(id uuid primary key default gen_random_uuid(),message_id uuid not null references public.messages(id) on delete cascade,conversation_id uuid not null references public.conversations(id) on delete cascade,provider text not null check(provider in('matrix','novu')),event_name text not null,payload jsonb not null default '{}'::jsonb,status text not null default 'pending' check(status in('pending','processing','sent','failed')),attempts integer not null default 0,last_error text,next_attempt_at timestamptz not null default now(),created_at timestamptz not null default now(),sent_at timestamptz,unique(message_id,provider));
alter table public.communication_delivery_outbox enable row level security; revoke all on public.communication_delivery_outbox from anon,authenticated; create index if not exists communication_delivery_outbox_pending_idx on public.communication_delivery_outbox(status,next_attempt_at);
create or replace function public.enqueue_message_delivery() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$ begin insert into public.communication_delivery_outbox(message_id,conversation_id,provider,event_name,payload) values(new.id,new.conversation_id,'matrix','message.created',jsonb_build_object('message_id',new.id,'conversation_id',new.conversation_id,'sender_id',new.sender_id,'body',new.body,'created_at',new.created_at)) on conflict(message_id,provider) do nothing; return new; end; $$;
revoke all on function public.enqueue_message_delivery() from public,anon,authenticated; drop trigger if exists messages_enqueue_communication_delivery on public.messages; create trigger messages_enqueue_communication_delivery after insert on public.messages for each row execute function public.enqueue_message_delivery();
create or replace function public.create_message_notification() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$ declare recipient uuid; begin for recipient in select cm.user_id from public.conversation_members cm where cm.conversation_id=new.conversation_id and cm.user_id<>new.sender_id loop insert into public.notifications(recipient_id,actor_id,kind,created_at,data,category,group_key,action_url,dedupe_key) values(recipient,new.sender_id,'message.received',new.created_at,jsonb_build_object('message_id',new.id,'conversation_id',new.conversation_id,'preview',left(new.body,180)),'messages','conversation:'||new.conversation_id::text,'/messages?conversation='||new.conversation_id::text,'message:'||new.id::text) on conflict(dedupe_key) do nothing; end loop; return new; end; $$;
revoke all on function public.create_message_notification() from public,anon,authenticated; drop trigger if exists messages_create_notification on public.messages; create trigger messages_create_notification after insert on public.messages for each row execute function public.create_message_notification();
create table if not exists public.matrix_identities(user_id uuid primary key references public.profiles(id) on delete cascade,matrix_user_id text not null unique,homeserver text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now()); alter table public.matrix_identities enable row level security; drop policy if exists matrix_identity_self_read on public.matrix_identities; create policy matrix_identity_self_read on public.matrix_identities for select to authenticated using(user_id=auth.uid()); revoke all on public.matrix_identities from anon; grant select on public.matrix_identities to authenticated;
create or replace function public.communication_list_messages(p_conversation_id uuid,p_limit integer default 50,p_cursor timestamptz default null) returns jsonb language sql security invoker set search_path=public as $$ select jsonb_build_object('items',coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at asc) from (select m.id,m.conversation_id,m.sender_id,m.body,m.media_url,m.media_type,m.created_at,m.edited_at,m.deleted_at,m.reply_to_message_id,m.shared_post_id,m.client_message_id,m.delivered_at,m.read_at,jsonb_build_object('id',p.id,'username',p.username,'display_name',p.display_name,'avatar_url',p.avatar_url,'verified',(p.verified_tier is not null and p.verified_tier<>'none')) sender from public.messages m join public.conversation_members cm on cm.conversation_id=m.conversation_id and cm.user_id=auth.uid() left join public.profiles p on p.id=m.sender_id where m.conversation_id=p_conversation_id and (p_cursor is null or m.created_at<p_cursor) order by m.created_at desc limit greatest(1,least(coalesce(p_limit,50),100))) x),'[]'::jsonb),'next_cursor',(select min(x.created_at)::text from (select m.created_at from public.messages m join public.conversation_members cm on cm.conversation_id=m.conversation_id and cm.user_id=auth.uid() where m.conversation_id=p_conversation_id and (p_cursor is null or m.created_at<p_cursor) order by m.created_at desc limit greatest(1,least(coalesce(p_limit,50),100))) x)); $$; grant execute on function public.communication_list_messages(uuid,integer,timestamptz) to authenticated;
do $$ begin insert into public.capability_registry(name,version,access,readonly,enabled,description) values('testagram.conversations.list',1,'authenticated',true,true,'List Testagram conversations'),('testagram.conversations.create',1,'authenticated',false,true,'Create a Testagram conversation'),('testagram.messages.list',1,'authenticated',true,true,'List conversation messages'),('testagram.messages.send',1,'authenticated',false,true,'Send an idempotent message'),('testagram.messages.mark_read',1,'authenticated',false,true,'Mark a message read'),('testagram.messages.react',1,'authenticated',false,true,'React to a message'),('testagram.calls.create',1,'authenticated',false,true,'Create a LiveKit call'),('testagram.calls.join',1,'authenticated',false,true,'Join a call'),('testagram.calls.end',1,'authenticated',false,true,'End a call'),('testagram.calls.token',1,'authenticated',true,true,'Return the LiveKit token endpoint contract'),('testagram.presence.read',1,'authenticated',true,true,'Read communication presence'),('testagram.presence.set',1,'authenticated',false,true,'Set communication presence') on conflict(name) do update set enabled=true,version=excluded.version,access=excluded.access,readonly=excluded.readonly,description=excluded.description,updated_at=now(); end $$;
-- The live project dispatcher is extended by the deployment migration; keep the capability names above in source control so drift is detectable by the contract gate.
