-- Testagram adaptation of ZenAd's decision/serving model.
-- Source: https://github.com/jwoerner42/ZenAd (Apache-2.0).
-- Testagram keeps identity/canonical data in Supabase and serves ad decisions
-- through Supabase Edge Functions; creatives may later move to Cloudflare R2.

create table if not exists public.zenad_apps (id text primary key,name text not null,slug text not null unique,enabled boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.zenad_slots (id text primary key,app_id text not null references public.zenad_apps(id) on delete cascade,code text not null,kind text not null default 'feed',floor_cpm_micros bigint not null default 0,enabled boolean not null default true,width integer,height integer,created_at timestamptz not null default now(),unique(app_id,code));
create table if not exists public.zenad_advertisers (id uuid primary key default gen_random_uuid(),name text not null,owner_user_id uuid references auth.users(id) on delete set null,status text not null default 'active',created_at timestamptz not null default now());
create table if not exists public.zenad_campaigns (id uuid primary key default gen_random_uuid(),advertiser_id uuid not null references public.zenad_advertisers(id) on delete cascade,name text not null,status text not null default 'draft',priority integer not null default 50,bid_cpm_micros bigint not null default 0,starts_at timestamptz not null default now(),ends_at timestamptz,daily_budget_micros bigint,targeting jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.zenad_campaign_apps (campaign_id uuid not null references public.zenad_campaigns(id) on delete cascade,app_id text not null references public.zenad_apps(id) on delete cascade,primary key(campaign_id,app_id));
create table if not exists public.zenad_creatives (id uuid primary key default gen_random_uuid(),campaign_id uuid not null references public.zenad_campaigns(id) on delete cascade,format text not null default 'display',headline text not null,body text,cta text not null default 'Learn more',asset_url text,click_through_url text not null,weight integer not null default 1,enabled boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.zenad_daily_spend (campaign_id uuid not null references public.zenad_campaigns(id) on delete cascade,spend_date date not null,spend_micros bigint not null default 0,impressions bigint not null default 0,clicks bigint not null default 0,primary key(campaign_id,spend_date));
create table if not exists public.zenad_impressions (id uuid primary key default gen_random_uuid(),request_id text not null,impression_id text not null unique,app_id text not null references public.zenad_apps(id) on delete cascade,slot_code text not null,campaign_id uuid not null references public.zenad_campaigns(id) on delete cascade,creative_id uuid not null references public.zenad_creatives(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,billable_micros bigint not null default 0,consent jsonb not null default '{}'::jsonb,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.zenad_events (id uuid primary key default gen_random_uuid(),impression_id text references public.zenad_impressions(impression_id) on delete cascade,event_type text not null,user_id uuid references auth.users(id) on delete set null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.zenad_frequency (user_id uuid not null references auth.users(id) on delete cascade,campaign_id uuid not null references public.zenad_campaigns(id) on delete cascade,window_start timestamptz not null,impressions integer not null default 0,primary key(user_id,campaign_id,window_start));

create index if not exists zenad_campaigns_status_idx on public.zenad_campaigns(status,starts_at,ends_at);
create index if not exists zenad_impressions_campaign_idx on public.zenad_impressions(campaign_id,created_at desc);
create index if not exists zenad_impressions_user_idx on public.zenad_impressions(user_id,created_at desc);
create index if not exists zenad_events_impression_idx on public.zenad_events(impression_id,created_at desc);

alter table public.zenad_apps enable row level security; alter table public.zenad_slots enable row level security; alter table public.zenad_advertisers enable row level security; alter table public.zenad_campaigns enable row level security; alter table public.zenad_campaign_apps enable row level security; alter table public.zenad_creatives enable row level security; alter table public.zenad_daily_spend enable row level security; alter table public.zenad_impressions enable row level security; alter table public.zenad_events enable row level security; alter table public.zenad_frequency enable row level security;

create or replace function public.is_platform_ad_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.platform_admins pa where pa.user_id=auth.uid() and pa.role in ('admin','super_admin','platform_admin')); $$;
revoke execute on function public.is_platform_ad_admin() from public,anon,authenticated; grant execute on function public.is_platform_ad_admin() to authenticated;

create policy zenad_admin_apps on public.zenad_apps for all to authenticated using(public.is_platform_ad_admin()) with check(public.is_platform_ad_admin());
create policy zenad_admin_slots on public.zenad_slots for all to authenticated using(public.is_platform_ad_admin()) with check(public.is_platform_ad_admin());
create policy zenad_admin_advertisers on public.zenad_advertisers for all to authenticated using(public.is_platform_ad_admin() or owner_user_id=auth.uid()) with check(public.is_platform_ad_admin() or owner_user_id=auth.uid());
create policy zenad_admin_campaigns on public.zenad_campaigns for all to authenticated using(public.is_platform_ad_admin() or exists(select 1 from public.zenad_advertisers a where a.id=advertiser_id and a.owner_user_id=auth.uid())) with check(public.is_platform_ad_admin() or exists(select 1 from public.zenad_advertisers a where a.id=advertiser_id and a.owner_user_id=auth.uid()));
create policy zenad_admin_campaign_apps on public.zenad_campaign_apps for all to authenticated using(public.is_platform_ad_admin()) with check(public.is_platform_ad_admin());
create policy zenad_admin_creatives on public.zenad_creatives for all to authenticated using(public.is_platform_ad_admin() or exists(select 1 from public.zenad_campaigns c join public.zenad_advertisers a on a.id=c.advertiser_id where c.id=campaign_id and a.owner_user_id=auth.uid())) with check(public.is_platform_ad_admin() or exists(select 1 from public.zenad_campaigns c join public.zenad_advertisers a on a.id=c.advertiser_id where c.id=campaign_id and a.owner_user_id=auth.uid()));
create policy zenad_admin_spend on public.zenad_daily_spend for select to authenticated using(public.is_platform_ad_admin());
create policy zenad_admin_impressions on public.zenad_impressions for select to authenticated using(public.is_platform_ad_admin() or user_id=auth.uid());
create policy zenad_admin_events on public.zenad_events for select to authenticated using(public.is_platform_ad_admin() or user_id=auth.uid());
create policy zenad_admin_frequency on public.zenad_frequency for select to authenticated using(public.is_platform_ad_admin() or user_id=auth.uid());

insert into public.zenad_apps(id,name,slug) values('testagram','Testagram','testagram') on conflict(id) do update set enabled=true;
insert into public.zenad_slots(id,app_id,code,kind,floor_cpm_micros,width,height) values ('testagram-feed-top','testagram','feed-top','feed',50000,728,90),('testagram-feed-inline','testagram','feed-inline','feed',50000,728,90),('testagram-profile','testagram','profile','profile',50000,728,90),('testagram-explore','testagram','explore','explore',50000,728,90) on conflict(id) do update set enabled=true;

-- Atomic impression claim: budget/floor/frequency checks and spend increment occur in one transaction.
create or replace function public.zenad_claim_impression(p_request_id text,p_impression_id text,p_app_id text,p_slot_code text,p_campaign_id uuid,p_creative_id uuid,p_user_id uuid,p_billable_micros bigint,p_consent jsonb default '{}'::jsonb,p_metadata jsonb default '{}'::jsonb) returns boolean language plpgsql security definer set search_path=public as $$ declare v_daily date:=current_date; v_spend bigint:=0; v_budget bigint; v_window timestamptz; v_count integer:=0; v_cap integer; begin select daily_budget_micros into v_budget from public.zenad_campaigns where id=p_campaign_id and status='active' for update; if not found then return false; end if; if exists(select 1 from public.zenad_campaigns c join public.zenad_slots s on s.app_id=p_app_id and s.code=p_slot_code where c.id=p_campaign_id and c.bid_cpm_micros < s.floor_cpm_micros) then return false; end if; select spend_micros into v_spend from public.zenad_daily_spend where campaign_id=p_campaign_id and spend_date=v_daily for update; if v_budget is not null and coalesce(v_spend,0)+p_billable_micros>v_budget then return false; end if; v_window:=date_trunc('day',now()); if p_user_id is not null then select coalesce((targeting->'frequencyCap'->>'maxImpressions')::integer,0) into v_cap from public.zenad_campaigns where id=p_campaign_id; if v_cap>0 then select impressions into v_count from public.zenad_frequency where user_id=p_user_id and campaign_id=p_campaign_id and window_start=v_window for update; if coalesce(v_count,0)>=v_cap then return false; end if; end if; end if; insert into public.zenad_daily_spend(campaign_id,spend_date,spend_micros,impressions) values(p_campaign_id,v_daily,p_billable_micros,1) on conflict(campaign_id,spend_date) do update set spend_micros=public.zenad_daily_spend.spend_micros+excluded.spend_micros,impressions=public.zenad_daily_spend.impressions+1; insert into public.zenad_impressions(request_id,impression_id,app_id,slot_code,campaign_id,creative_id,user_id,billable_micros,consent,metadata) values(p_request_id,p_impression_id,p_app_id,p_slot_code,p_campaign_id,p_creative_id,p_user_id,p_billable_micros,p_consent,p_metadata); if p_user_id is not null and v_cap>0 then insert into public.zenad_frequency(user_id,campaign_id,window_start,impressions) values(p_user_id,p_campaign_id,v_window,1) on conflict(user_id,campaign_id,window_start) do update set impressions=public.zenad_frequency.impressions+1; end if; return true; end; $$;
create or replace function public.zenad_record_click(p_impression_id text) returns boolean language plpgsql security definer set search_path=public as $$ declare v_campaign uuid; begin select campaign_id into v_campaign from public.zenad_impressions where impression_id=p_impression_id for update; if not found then return false; end if; insert into public.zenad_events(impression_id,event_type,user_id) select p_impression_id,'click',user_id from public.zenad_impressions where impression_id=p_impression_id; update public.zenad_daily_spend set clicks=clicks+1 where campaign_id=v_campaign and spend_date=current_date; return true; end; $$;
revoke execute on function public.zenad_claim_impression(text,text,text,text,uuid,uuid,uuid,bigint,jsonb,jsonb) from public,anon,authenticated;
revoke execute on function public.zenad_record_click(text) from public,anon,authenticated;
