-- Reconcile browser communications with canonical call_sessions/messages contracts.
create or replace function public.capability_dispatch(p_capability text, p_input jsonb default '{}'::jsonb)
returns jsonb language plpgsql set search_path='public' as $function$
declare v_user_id uuid:=auth.uid(); v_limit int:=least(100,greatest(1,coalesce((p_input->>'limit')::int,20))); v_id uuid; v_conversation uuid;
begin
  p_capability:=btrim(coalesce(p_capability,''));
  if p_capability not in ('testagram.capabilities.list','testagram.health.read') and v_user_id is null then raise exception using errcode='28000',message='Authentication required'; end if;
  case p_capability
    when 'testagram.conversations.list' then
      return jsonb_build_object('items',coalesce((select jsonb_agg(x.obj order by x.updated_at desc) from (select c.updated_at,jsonb_build_object('id',c.id,'created_at',c.created_at,'updated_at',c.updated_at,'kind',c.kind,'title',c.title,'members',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'username',p.username,'display_name',p.display_name,'avatar_url',p.avatar_url,'verified',(p.verified_tier is not null and p.verified_tier<>'none')) order by p.username) from public.conversation_members cm join public.profiles p on p.id=cm.user_id where cm.conversation_id=c.id and cm.left_at is null),'[]'::jsonb),'unread_count',coalesce((select count(*) from public.messages m join public.conversation_members me on me.conversation_id=m.conversation_id and me.user_id=v_user_id where m.conversation_id=c.id and m.sender_id<>v_user_id and m.created_at>coalesce(me.last_read_at,'epoch'::timestamptz) and m.deleted_at is null),0),'latest_message',(select to_jsonb(lm) from public.messages lm where lm.conversation_id=c.id and lm.deleted_at is null order by lm.created_at desc limit 1)) obj from public.conversations c where exists(select 1 from public.conversation_members cm where cm.conversation_id=c.id and cm.user_id=v_user_id and cm.left_at is null) order by c.updated_at desc limit v_limit)x),'[]'::jsonb),'next_cursor',null);
    when 'testagram.conversations.create' then
      if jsonb_typeof(p_input->'member_ids')<>'array' or jsonb_array_length(p_input->'member_ids')<1 then raise exception using errcode='22023',message='At least one member is required'; end if;
      if jsonb_array_length(p_input->'member_ids')=1 then select c.id into v_conversation from public.conversations c where c.kind='direct' and exists(select 1 from public.conversation_members cm where cm.conversation_id=c.id and cm.user_id=v_user_id and cm.left_at is null) and (select count(*) from public.conversation_members cm2 where cm2.conversation_id=c.id and cm2.left_at is null)=2 and exists(select 1 from public.conversation_members cm3 where cm3.conversation_id=c.id and cm3.user_id=(p_input->'member_ids'->>0)::uuid and cm3.left_at is null) limit 1; end if;
      if v_conversation is null then insert into public.conversations(created_by,kind,title,encrypted) values(v_user_id,case when jsonb_array_length(p_input->'member_ids')>1 then 'group' else 'direct' end,nullif(p_input->>'title',''),true) returning id into v_conversation; insert into public.conversation_members(conversation_id,user_id,role) values(v_conversation,v_user_id,'owner'); insert into public.conversation_members(conversation_id,user_id,role) select v_conversation,x::uuid,'member' from jsonb_array_elements_text(p_input->'member_ids') x where x::uuid<>v_user_id on conflict do nothing; end if;
      return jsonb_build_object('conversation_id',v_conversation);
    when 'testagram.messages.list' then
      return jsonb_build_object('items',coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at asc) from (select m.id,m.conversation_id,m.sender_id,m.body,m.media_url,m.media_type,m.created_at,m.edited_at,m.deleted_at,m.reply_to_message_id,m.shared_post_id,m.client_message_id,m.delivered_at,m.read_at,m.e2ee_enabled,m.e2ee_version,m.e2ee_epoch,m.ciphertext,m.nonce,m.aad,jsonb_build_object('id',p.id,'username',p.username,'display_name',p.display_name,'avatar_url',p.avatar_url,'verified',(p.verified_tier is not null and p.verified_tier<>'none')) sender,m.attachment_metadata from public.messages m join public.conversation_members cm on cm.conversation_id=m.conversation_id and cm.user_id=v_user_id and cm.left_at is null left join public.profiles p on p.id=m.sender_id where m.conversation_id=(p_input->>'conversation_id')::uuid and (nullif(p_input->>'cursor','') is null or m.created_at<(p_input->>'cursor')::timestamptz) order by m.created_at desc limit v_limit)x),'[]'::jsonb),'next_cursor',(select min(x.created_at)::text from (select m.created_at from public.messages m join public.conversation_members cm on cm.conversation_id=m.conversation_id and cm.user_id=v_user_id and cm.left_at is null where m.conversation_id=(p_input->>'conversation_id')::uuid and (nullif(p_input->>'cursor','') is null or m.created_at<(p_input->>'cursor')::timestamptz) order by m.created_at desc limit v_limit)x));
    when 'testagram.messages.send_encrypted' then
      if not exists(select 1 from public.conversation_members cm where cm.conversation_id=(p_input->>'conversation_id')::uuid and cm.user_id=v_user_id and cm.left_at is null) then raise exception using errcode='42501',message='Conversation membership required'; end if;
      insert into public.messages(conversation_id,sender_id,body,client_message_id,ciphertext,nonce,aad,e2ee_enabled,e2ee_version,e2ee_epoch,key_epoch,message_type,reply_to_id,attachment_metadata) values((p_input->>'conversation_id')::uuid,v_user_id,'',nullif(p_input->>'client_message_id',''),p_input->>'ciphertext',p_input->>'nonce',p_input->>'aad',true,coalesce(nullif(p_input->>'e2ee_version',''),'v1'),coalesce((p_input->>'e2ee_epoch')::int,1),coalesce((p_input->>'e2ee_epoch')::bigint,1),'text',nullif(p_input->>'reply_to_message_id','')::uuid,'[]'::jsonb) on conflict(sender_id,client_message_id) where client_message_id is not null do nothing returning id into v_id;
      if v_id is null then select id into v_id from public.messages where sender_id=v_user_id and client_message_id=nullif(p_input->>'client_message_id','') limit 1; end if; if v_id is null then raise exception 'MESSAGE_NOT_CREATED'; end if;
      return jsonb_build_object('message_id',v_id,'encrypted',true);
    when 'testagram.messages.edit_encrypted' then update public.messages set body='',ciphertext=p_input->>'ciphertext',nonce=p_input->>'nonce',aad=p_input->>'aad',e2ee_enabled=true,e2ee_version=coalesce(nullif(p_input->>'e2ee_version',''),'v1'),e2ee_epoch=coalesce((p_input->>'e2ee_epoch')::int,e2ee_epoch),edited_at=now(),updated_at=now() where id=(p_input->>'message_id')::uuid and sender_id=v_user_id and deleted_at is null; if not found then raise exception 'MESSAGE_NOT_FOUND'; end if; return jsonb_build_object('message_id',(p_input->>'message_id')::uuid,'edited',true);
    when 'testagram.messages.delete' then update public.messages set deleted_at=now(),updated_at=now() where id=(p_input->>'message_id')::uuid and sender_id=v_user_id and deleted_at is null; if not found then raise exception 'MESSAGE_NOT_FOUND'; end if; return jsonb_build_object('message_id',(p_input->>'message_id')::uuid,'deleted',true);
    when 'testagram.messages.mark_read' then update public.conversation_members cm set last_read_at=greatest(coalesce(cm.last_read_at,'epoch'::timestamptz),coalesce(m.created_at,now())) from public.messages m where m.id=(p_input->>'message_id')::uuid and cm.conversation_id=m.conversation_id and cm.user_id=v_user_id; return jsonb_build_object('message_id',(p_input->>'message_id')::uuid,'read',true);
    when 'testagram.messages.react' then if coalesce((p_input->>'remove')::boolean,false) then delete from public.message_reactions where message_id=(p_input->>'message_id')::uuid and user_id=v_user_id and emoji=coalesce(nullif(p_input->>'reaction',''),'❤️'); return jsonb_build_object('message_id',(p_input->>'message_id')::uuid,'reaction',coalesce(nullif(p_input->>'reaction',''),'❤️'),'removed',true); end if; insert into public.message_reactions(message_id,user_id,emoji) values((p_input->>'message_id')::uuid,v_user_id,coalesce(nullif(p_input->>'reaction',''),'❤️')) on conflict(message_id,user_id) do update set emoji=excluded.emoji; return jsonb_build_object('message_id',(p_input->>'message_id')::uuid,'reaction',coalesce(nullif(p_input->>'reaction',''),'❤️'),'removed',false);
    when 'testagram.calls.create' then insert into public.call_sessions(conversation_id,created_by,provider,room_name,kind,status,e2ee_enabled,e2ee_epoch) values((p_input->>'conversation_id')::uuid,v_user_id,'livekit',coalesce(nullif(p_input->>'room_name',''),'testagram-'||replace(gen_random_uuid()::text,'-','')),coalesce(nullif(p_input->>'kind',''),'video'),'ringing',true,coalesce((p_input->>'e2ee_epoch')::int,1)) returning id into v_id; insert into public.call_participants(call_id,user_id,joined_at) values(v_id,v_user_id,now()) on conflict do nothing; return jsonb_build_object('call_id',v_id,'provider','livekit','room_name',(select room_name from public.call_sessions where id=v_id),'kind',(select kind from public.call_sessions where id=v_id),'created_by',v_user_id,'status','ringing','conversation_id',(p_input->>'conversation_id')::uuid);
    when 'testagram.calls.join' then update public.call_sessions c set status=case when c.status='ringing' then 'active' else c.status end,started_at=coalesce(c.started_at,now()) where c.id=(p_input->>'call_id')::uuid and c.status<>'ended' and exists(select 1 from public.conversation_members cm where cm.conversation_id=c.conversation_id and cm.user_id=v_user_id and cm.left_at is null); if not found then raise exception 'CALL_NOT_AVAILABLE'; end if; insert into public.call_participants(call_id,user_id,joined_at) values((p_input->>'call_id')::uuid,v_user_id,now()) on conflict(call_id,user_id) do update set joined_at=excluded.joined_at,left_at=null; return jsonb_build_object('call_id',(p_input->>'call_id')::uuid,'joined',true);
    when 'testagram.calls.end' then update public.call_sessions c set status='ended',ended_at=coalesce(c.ended_at,now()) where c.id=(p_input->>'call_id')::uuid and (c.created_by=v_user_id or exists(select 1 from public.call_participants cp where cp.call_id=c.id and cp.user_id=v_user_id)); update public.call_participants set left_at=coalesce(left_at,now()) where call_id=(p_input->>'call_id')::uuid and user_id=v_user_id; return jsonb_build_object('call_id',(p_input->>'call_id')::uuid,'ended',true);
    else return public.capability_dispatch_legacy(p_capability,p_input);
  end case;
end;
$function$;