type claims struct { Mode string \`json:"mode"\`; RoomID string \`json:"room_id"\`; Role string \`json:"role"\`; UserID string \`json:"user_id"\`; Exp int64 \`json:"exp"\` }
type signal struct { Type string \`json:"type"\`; SDP string \`json:"sdp,omitempty"\`; Candidate *webrtc.ICECandidateInit \`json:"candidate,omitempty"\`; ViewerCount int \`json:"viewer_count,omitempty"\`; GuestCount int \`json:"guest_count,omitempty"\`; ParticipantCount int \`json:"participant_count,omitempty"\` }
type peer struct { ws *websocket.Conn; pc *webrtc.PeerConnection; mode, role, userID string; mu sync.Mutex; writeMu sync.Mutex; senders map[*publishedTrack]*webrtc.RTPSender }
type publishedTrack struct { owner *peer; local *webrtc.TrackLocalStaticRTP; key string; kind webrtc.RTPCodecType }
type room struct { mode, id string; mu sync.Mutex; peers map[*peer]bool; host *peer; tracks map[string]*publishedTrack }

var rooms sync.Map
var rateMu sync.Mutex
var connectionRates = map[string]rateEntry{}
type rateEntry struct { started time.Time; count int }
var totalConnections atomic.Uint64
var rejectedConnections atomic.Uint64
var rtpPackets atomic.Uint64
var rtpWriteErrors atomic.Uint64

func checkOrigin(r *http.Request) bool { raw:=strings.TrimSpace(os.Getenv("MEDIA_ENGINE_ALLOWED_ORIGINS")); if raw=="" { return true }; origin:=strings.TrimRight(strings.TrimSpace(r.Header.Get("Origin")),"/"); for _,allowed:=range strings.Split(raw,",") { if origin==strings.TrimRight(strings.TrimSpace(allowed),"/") { return true } }; return false }
var upgrader = websocket.Upgrader{CheckOrigin: checkOrigin}
func decodePart(v string)([]byte,error){ return base64.RawURLEncoding.DecodeString(v) }
func verifyToken(token,secret string)(*claims,error){ parts:=strings.Split(token,"."); if len(parts)!=3{return nil,fmt.Errorf("invalid media token")}; header,err:=decodePart(parts[0]);if err!=nil||string(header)!="testagram-media-v1"{return nil,fmt.Errorf("invalid media token header")}; payload,err:=decodePart(parts[1]);if err!=nil{return nil,err};sig,err:=decodePart(parts[2]);if err!=nil{return nil,err};mac:=hmac.New(sha256.New,[]byte(secret));_,_=mac.Write(payload);if !hmac.Equal(sig,mac.Sum(nil)){return nil,fmt.Errorf("invalid media token signature")};var c claims;if err=json.Unmarshal(payload,&c);err!=nil{return nil,err};if c.RoomID==""||c.Mode==""||c.Role==""||time.Now().Unix()>=c.Exp{return nil,fmt.Errorf("expired media token")};switch c.Mode{case "tv":if c.Role!="host"&&c.Role!="viewer"&&c.Role!="guest"{return nil,fmt.Errorf("invalid tv role")};case "space":if c.Role!="host"&&c.Role!="listener"&&c.Role!="speaker"{return nil,fmt.Errorf("invalid space role")};case "call":if c.Role!="participant"{return nil,fmt.Errorf("invalid call role")};default:return nil,fmt.Errorf("invalid media mode")};return &c,nil}
func send(ws *websocket.Conn,m signal)error{_ = ws.SetWriteDeadline(time.Now().Add(10*time.Second));return ws.WriteJSON(m)}
func (p *peer) send(m signal)error{p.writeMu.Lock();defer p.writeMu.Unlock();return send(p.ws,m)}
func getRoom(mode,id string)*room{key:=mode+":"+id;v,_:=rooms.LoadOrStore(key,&room{mode:mode,id:id,peers:map[*peer]bool{},tracks:map[string]*publishedTrack{}});return v.(*room)}
func presence(r *room) signal{r.mu.Lock();defer r.mu.Unlock();viewers,guests,participants:=0,0,0;for p:=range r.peers{switch{case r.mode=="tv"&&p.role=="viewer":viewers++;case r.mode=="tv"&&p.role=="guest":guests++;default:participants++}};return signal{Type:"presence",ViewerCount:viewers,GuestCount:guests,ParticipantCount:participants}}
func broadcastPresence(r *room){r.mu.Lock();peers:=make([]*peer,0,len(r.peers));for p:=range r.peers{peers=append(peers,p)};r.mu.Unlock();m:=presence(r);for _,p:=range peers{_ = p.send(m)}}
func closePeer(p *peer){if p==nil{return};_=p.ws.Close();_=p.pc.Close()}

func connectionAllowed(ip string) bool {
  limit := envInt("MEDIA_ENGINE_CONNECTIONS_PER_MINUTE", 60)
  key := "rate:" + ip
  now := time.Now()
  rateMu.Lock()
  defer rateMu.Unlock()
  for k, entry := range connectionRates {
    if now.Sub(entry.started) >= time.Minute { delete(connectionRates,k) }
  }
  entry := connectionRates[key]
  if entry.started.IsZero() || now.Sub(entry.started) >= time.Minute {
    connectionRates[key] = rateEntry{started: now, count: 1}
    return true
  }
  if entry.count >= limit { return false }
  entry.count++
  connectionRates[key] = entry
  return true
}

func roomLimitReached(r *room,role string)bool{r.mu.Lock();defer r.mu.Unlock();switch r.mode{case "tv":if role=="viewer"{n:=0;for p:=range r.peers{if p.role=="viewer"{n++}};return n>=envInt("MEDIA_ENGINE_MAX_VIEWERS",500)};if role=="guest"{n:=0;for p:=range r.peers{if p.role=="guest"{n++}};return n>=envInt("MEDIA_ENGINE_MAX_GUESTS",4)}};if r.mode=="space"{return len(r.peers)>=envInt("MEDIA_ENGINE_MAX_SPACE_PARTICIPANTS",1000)};if r.mode=="call"{return len(r.peers)>=envInt("MEDIA_ENGINE_MAX_CALL_PARTICIPANTS",25)};return true}
func shouldReceive(r *room,target,owner *peer)bool{if target==owner{return false};switch r.mode{case "tv":if owner.role=="host"{return target.role=="viewer"||target.role=="guest"};if owner.role=="guest"{return target.role=="host"};return false;case "space","call":return true};return false}
func renegotiatePeer(p *peer){if p.pc.ConnectionState()==webrtc.PeerConnectionStateClosed{return};for i:=0;i<20;i++{p.mu.Lock();stable:=p.pc.SignalingState()==webrtc.SignalingStateStable;p.mu.Unlock();if stable{break};time.Sleep(50*time.Millisecond)};p.mu.Lock();defer p.mu.Unlock();if p.pc.SignalingState()!=webrtc.SignalingStateStable{return};offer,err:=p.pc.CreateOffer(nil);if err!=nil{return};if err=p.pc.SetLocalDescription(offer);err!=nil{return};<-webrtc.GatheringCompletePromise(p.pc);if local:=p.pc.LocalDescription();local!=nil{_ = p.send(signal{Type:"offer",SDP:local.SDP})}}
func attachTrack(r *room,target *peer,t *publishedTrack){if !shouldReceive(r,target,t.owner){return};target.mu.Lock();if _,ok:=target.senders[t];ok{target.mu.Unlock();return};sender,err:=target.pc.AddTrack(t.local);if err==nil{target.senders[t]=sender};target.mu.Unlock();if err==nil{go renegotiatePeer(target)}}
func removeTrackFromTargets(r *room,t *publishedTrack){r.mu.Lock();targets:=make([]*peer,0,len(r.peers));for p:=range r.peers{if p!=t.owner{targets=append(targets,p)}};r.mu.Unlock();for _,target:=range targets{target.mu.Lock();sender:=target.senders[t];delete(target.senders,t);if sender!=nil{_ = target.pc.RemoveTrack(sender)};target.mu.Unlock();if sender!=nil{go renegotiatePeer(target)}}}
func removePublishedTrack(r *room,t *publishedTrack){r.mu.Lock();if current:=r.tracks[t.key];current!=t{r.mu.Unlock();return};delete(r.tracks,t.key);r.mu.Unlock();removeTrackFromTargets(r,t)}
func publishTrack(r *room,owner *peer,remote *webrtc.TrackRemote){key:=owner.userID+":"+remote.ID()+":"+string(remote.Kind());local,err:=webrtc.NewTrackLocalStaticRTP(remote.Codec().RTPCodecCapability,key,"testagram");if err!=nil{return};t:=&publishedTrack{owner:owner,local:local,key:key,kind:remote.Kind()};r.mu.Lock();if _,exists:=r.tracks[key];exists{r.mu.Unlock();return};r.tracks[key]=t;targets:=make([]*peer,0,len(r.peers));for p:=range r.peers{if shouldReceive(r,p,owner){targets=append(targets,p)}};r.mu.Unlock();for _,target:=range targets{attachTrack(r,target,t)};go func(){defer removePublishedTrack(r,t);for{packet,_,err:=remote.ReadRTP();if err!=nil{return};rtpPackets.Add(1);if err:=local.WriteRTP(packet);err!=nil{rtpWriteErrors.Add(1)}}}()}
func handleOffer(p *peer,sdp string)error{if err:=p.pc.SetRemoteDescription(webrtc.SessionDescription{Type:webrtc.SDPTypeOffer,SDP:sdp});err!=nil{return err};answer,err:=p.pc.CreateAnswer(nil);if err!=nil{return err};if err=p.pc.SetLocalDescription(answer);err!=nil{return err};<-webrtc.GatheringCompletePromise(p.pc);if local:=p.pc.LocalDescription();local!=nil{return p.send(signal{Type:"answer",SDP:local.SDP})};return nil}
func handlePeer(p *peer,r *room){done:=make(chan struct{});defer close(done);go func(){ticker:=time.NewTicker(20*time.Second);defer ticker.Stop();for{select{case<-ticker.C:p.writeMu.Lock();_=p.ws.SetWriteDeadline(time.Now().Add(10*time.Second));err:=p.ws.WriteMessage(websocket.PingMessage,nil);p.writeMu.Unlock();if err!=nil{_=p.ws.Close();return};case<-done:return}}}();defer func(){r.mu.Lock();wasHost:=r.host==p;delete(r.peers,p);if wasHost{r.host=nil};tracks:=make([]*publishedTrack,0);for _,t:=range r.tracks{if t.owner==p{tracks=append(tracks,t)}};others:=make([]*peer,0,len(r.peers));if wasHost&&(r.mode=="tv"||r.mode=="space"){for other:=range r.peers{others=append(others,other)}};empty:=len(r.peers)==0;r.mu.Unlock();for _,t:=range tracks{removePublishedTrack(r,t)};for _,other:=range others{go closePeer(other)};broadcastPresence(r);if empty{rooms.Delete(r.mode+":"+r.id)}}();p.ws.SetReadLimit(1<<20);_=p.ws.SetReadDeadline(time.Now().Add(45*time.Second));p.ws.SetPongHandler(func(string)error{return p.ws.SetReadDeadline(time.Now().Add(45*time.Second))});p.pc.OnConnectionStateChange(func(state webrtc.PeerConnectionState){if state==webrtc.PeerConnectionStateFailed||state==webrtc.PeerConnectionStateClosed{_=p.ws.Close()}});p.pc.OnTrack(func(track *webrtc.TrackRemote,_ *webrtc.RTPReceiver){if track.Kind()!=webrtc.RTPCodecTypeVideo&&track.Kind()!=webrtc.RTPCodecTypeAudio{return};if p.mode=="tv"&&p.role=="viewer"{return};if p.mode=="space"&&p.role=="listener"{return};publishTrack(r,p,track)});for{_=p.ws.SetReadDeadline(time.Now().Add(45*time.Second));var m signal;if err:=p.ws.ReadJSON(&m);err!=nil{return};switch m.Type{case "offer":if err:=handleOffer(p,m.SDP);err!=nil{return};case "answer":if err:=p.pc.SetRemoteDescription(webrtc.SessionDescription{Type:webrtc.SDPTypeAnswer,SDP:m.SDP});err!=nil{return};case "candidate":if m.Candidate!=nil{_=p.pc.AddICECandidate(*m.Candidate)}}}}
func iceServers()[]webrtc.ICEServer{servers:=[]webrtc.ICEServer{{URLs:[]string{"stun:stun.l.google.com:19302"}}};raw:=strings.TrimSpace(os.Getenv("MEDIA_ENGINE_ICE_SERVERS"));if raw==""{return servers};var extra []webrtc.ICEServer;if json.Unmarshal([]byte(raw),&extra)==nil{servers=append(servers,extra...)};return servers}
func wsHandler(w http.ResponseWriter,req *http.Request){totalConnections.Add(1);secret:=os.Getenv("MEDIA_ENGINE_SECRET");if secret==""{http.Error(w,"media engine not configured",503);return};c,err:=verifyToken(req.URL.Query().Get("token"),secret);if err!=nil{rejectedConnections.Add(1);http.Error(w,"unauthorized",401);return};remoteIP,_,_:=net.SplitHostPort(req.RemoteAddr);if !connectionAllowed(remoteIP){rejectedConnections.Add(1);http.Error(w,"rate limited",429);return};r:=getRoom(c.Mode,c.RoomID);if roomLimitReached(r,c.Role){rejectedConnections.Add(1);http.Error(w,"room limit reached",429);return};conn,err:=upgrader.Upgrade(w,req,nil);if err!=nil{return};setting:=webrtc.SettingEngine{};udpMin:=envInt("MEDIA_ENGINE_UDP_MIN",10000);udpMax:=envInt("MEDIA_ENGINE_UDP_MAX",20000);if udpMin>=udpMax||udpMax>65535{udpMin,udpMax=10000,20000};_=setting.SetEphemeralUDPPortRange(uint16(udpMin),uint16(udpMax));setting.SetICEMulticastDNSMode(ice.MulticastDNSModeDisabled);publicIP:=strings.TrimSpace(os.Getenv("MEDIA_ENGINE_PUBLIC_IP"));if publicIP!=""{setting.SetNAT1To1IPs([]string{publicIP},webrtc.ICECandidateTypeHost)};media:=&webrtc.MediaEngine{};if err:=media.RegisterDefaultCodecs();err!=nil{_=conn.Close();return};api:=webrtc.NewAPI(webrtc.WithSettingEngine(setting),webrtc.WithMediaEngine(media));pc,err:=api.NewPeerConnection(webrtc.Configuration{ICEServers:iceServers()});if err!=nil{_=conn.Close();return};p:=&peer{ws:conn,pc:pc,mode:c.Mode,role:c.Role,userID:c.UserID,senders:map[*publishedTrack]*webrtc.RTPSender{}};r.mu.Lock();if c.Role=="host"{if r.host!=nil{r.mu.Unlock();closePeer(p);return};r.host=p};r.peers[p]=true;r.mu.Unlock();broadcastPresence(r);go handlePeer(p,r)}
func health(w http.ResponseWriter,_ *http.Request){ready:=strings.TrimSpace(os.Getenv("MEDIA_ENGINE_SECRET"))!="";status:=http.StatusOK;if !ready{status=http.StatusServiceUnavailable};w.Header().Set("content-type","application/json");w.WriteHeader(status);_=json.NewEncoder(w).Encode(map[string]any{"ok":ready,"service":"testagram-media-engine","transport":"native-webrtc-sfu","rooms":countRooms(),"features":[]string{"websocket-signaling","tv-broadcast","audio-spaces","group-calls","stun","turn-config","rtp-forwarding","room-isolation","presence","rate-limits","metrics"}})}
func countRooms()int{count:=0;rooms.Range(func(_, _ any)bool{count++;return true});return count}
func metrics(w http.ResponseWriter,_ *http.Request){w.Header().Set("content-type","text/plain; version=0.0.4");fmt.Fprintf(w,"testagram_media_connections_total %d\n",totalConnections.Load());fmt.Fprintf(w,"testagram_media_connections_rejected_total %d\n",rejectedConnections.Load());fmt.Fprintf(w,"testagram_media_rtp_packets_total %d\n",rtpPackets.Load());fmt.Fprintf(w,"testagram_media_rtp_write_errors_total %d\n",rtpWriteErrors.Load());fmt.Fprintf(w,"testagram_media_active_rooms %d\n",countRooms())}
func main(){mux:=http.NewServeMux();mux.HandleFunc("/healthz",health);mux.HandleFunc("/readyz",health);mux.HandleFunc("/metrics",metrics);mux.HandleFunc("/ws",wsHandler);port:=os.Getenv("PORT");if port==""{port="8080"};log.Printf("Testagram Media Engine listening on :%s",port);log.Fatal(http.ListenAndServe(":"+port,mux))}
