import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")||"";
const ORIGIN="https://federation.testagram.site";
const CTX=["https://www.w3.org/ns/activitystreams","https://w3id.org/security/v1"];
const AP='application/ld+json; profile="https://www.w3.org/ns/activitystreams", application/activity+json';
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-federation-internal","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const json=(v:unknown,status=200)=>new Response(JSON.stringify(v),{status,headers:{...CORS,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const enc=(v:string)=>encodeURIComponent(v);
async function db(path:string,init:RequestInit={}){if(!SERVICE_KEY)throw Error("Federation service credential is not configured");const h=new Headers(init.headers);h.set("apikey",SERVICE_KEY);h.set("Authorization",`Bearer ${SERVICE_KEY}`);h.set("Content-Type","application/json");const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:h});if(!r.ok)throw Error(`database ${r.status}: ${(await r.text()).slice(0,800)}`);return r;}
function internal(req:Request){const t=req.headers.get("x-federation-internal"),a=req.headers.get("authorization");return Boolean(SERVICE_KEY&&(t===SERVICE_KEY||a===`Bearer ${SERVICE_KEY}`));}
async function actorForUser(uid:string){const r=await db(`federation_actors?user_id=eq.${enc(uid)}&select=*`);const rows=await r.json() as any[];if(!rows[0])throw Error("Local federation actor not found");return rows[0];}
async function sign(local:any,url:string,method:"GET"|"POST",body=""){const target=new URL(url),date=new Date().toUTCString();const key=await crypto.subtle.importKey("jwk",local.private_key_jwk,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const digest=body?`sha-256=${btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(body)))))}`:"";const lines=[`(request-target): ${method.toLowerCase()} ${target.pathname}${target.search}`,`host: ${target.host}`,`date: ${date}`];if(body)lines.push(`digest: ${digest}`);const signature=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,new TextEncoder().encode(lines.join("\n")));const headers:Record<string,string>={Date:date,Accept:AP,Signature:`keyId="${local.actor_url}#main-key",algorithm="rsa-sha256",headers="${lines.map(x=>x.split(":")[0]).join(" ")}",signature="${btoa(String.fromCharCode(...new Uint8Array(signature)))}"`,"User-Agent":"Testagram-Federation/3.0"};if(body){headers.Digest=digest;headers["Content-Type"]='application/ld+json; profile="https://www.w3.org/ns/activitystreams"';}return headers;}
async function remoteActor(local:any,url:string){const headers=await sign(local,url,"GET");const r=await fetch(url,{headers});const text=await r.text();if(!r.ok)throw Error(`remote actor ${r.status}: ${text.slice(0,1200)}`);const a=JSON.parse(text);if(!a?.id||!a?.inbox||!a?.publicKey?.publicKeyPem)throw Error("Remote actor does not satisfy ActivityPub actor contract");return a;}
async function resolve(local:any,target:string){let actorUrl=String(target||"").trim().replace(/^@/,"");if(!actorUrl.startsWith("http://")&&!actorUrl.startsWith("https://")){const parts=actorUrl.split("@");if(parts.length!==2||!parts[0]||!parts[1])throw Error("Expected @user@domain or ActivityPub actor URL");const [username,domain]=parts;const resource=encodeURIComponent(`acct:${username}@${domain}`);const r=await fetch(`https://${domain}/.well-known/webfinger?resource=${resource}`,{headers:{Accept:"application/jrd+json, application/json","User-Agent":"Testagram-Federation/3.0"}});if(!r.ok)throw Error(`WebFinger ${r.status} for ${domain}`);const finger=await r.json();actorUrl=(finger.links||[]).find((l:any)=>l.rel==="self"&&l.href&&String(l.type||"").includes("activity"))?.href||"";if(!actorUrl)throw Error("WebFinger did not return an ActivityPub actor");}const actor=await remoteActor(local,actorUrl),canonical=String(actor.id||actorUrl),inbox=String(actor.endpoints?.sharedInbox||actor.inbox||"");if(!canonical.startsWith("https://")||!inbox.startsWith("https://"))throw Error("Remote actor exposes an invalid HTTPS actor/inbox");await db("federation_remote_actors?on_conflict=actor_url",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({actor_url:canonical,acct:actor.preferredUsername?`${actor.preferredUsername}@${new URL(canonical).hostname}`:null,username:actor.preferredUsername||null,domain:new URL(canonical).hostname,inbox_url:actor.inbox||null,shared_inbox_url:actor.endpoints?.sharedInbox||null,actor,fetched_at:new Date().toISOString(),updated_at:new Date().toISOString()})});return{actorUrl:canonical,inbox,actor};}
async function queue(local:any,userId:string,inbox:string,activity:any){const now=new Date().toISOString();const a=await db("federated_activities?on_conflict=uri",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({uri:activity.id,activity_type:activity.type,actor_uri:activity.actor,object_uri:typeof activity.object==="string"?activity.object:(activity.object?.id||null),target_uri:typeof activity.target==="string"?activity.target:(activity.target?.id||null),raw_activity:activity,received_at:now,processed_at:now,processing_state:"processed",processing_attempts:0,direction:"outbound",local_user_id:userId})});const ar=await a.json() as any[];const activityId=ar[0]?.id;if(!activityId)throw Error("Failed to persist federation activity");const d=await db("federation_deliveries?on_conflict=activity_id,target_inbox",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({activity_id:activityId,target_inbox:inbox,instance_domain:new URL(inbox).hostname,status:"pending",attempt_count:0,next_attempt_at:now,activity_payload:activity})});const dr=await d.json() as any[];const deliveryId=dr[0]?.id||null;await db("federation_outbox",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({user_id:userId,activity_id:activity.id,activity_type:activity.type,actor_url:local.actor_url,inbox_url:inbox,payload:activity,status:"pending",attempts:0,next_attempt_at:now,last_error:null})});return{status:"queued",activityId:activity.id,deliveryId};}
async function relationship(uid:string,actorUrl:string){const r=await db(`federated_follow_relationships?local_user_id=eq.${enc(uid)}&remote_actor_uri=eq.${enc(actorUrl)}&select=*`);const rows=await r.json() as any[];return rows[0]||null;}
async function upsertRelationship(values:Record<string,unknown>){await db("federated_follow_relationships?on_conflict=local_user_id,remote_actor_uri",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(values)});}
async function stableActivityId(localActor:string,remoteActor:string,kind:"follow"|"undo"){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(`${kind}|${localActor}|${remoteActor}`));const hex=Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,"0")).join("");return`${localActor}#activities/${kind}-${hex.slice(0,48)}`;}
async function follow(uid:string,local:any,target:string){const remote=await resolve(local,target),existing=await relationship(uid,remote.actorUrl),activityId=existing?.follow_activity_uri||await stableActivityId(local.actor_url,remote.actorUrl,"follow");if(existing?.state==="pending"||existing?.state==="accepted")return{ok:true,idempotent:true,state:existing.state,actorUrl:remote.actorUrl,inbox:existing.remote_inbox_uri||remote.inbox,followActivityUri:activityId,deliveryState:existing.delivery_state||null};const now=new Date().toISOString();await upsertRelationship({local_user_id:uid,remote_actor_uri:remote.actorUrl,state:"pending",follow_activity_uri:activityId,remote_inbox_uri:remote.inbox,delivery_state:"queued",delivery_attempts:0,last_error:null,updated_at:now});const activity={"@context":CTX,id:activityId,type:"Follow",actor:local.actor_url,object:remote.actorUrl};const q=await queue(local,uid,remote.inbox,activity);return{ok:true,state:"pending",actorUrl:remote.actorUrl,inbox:remote.inbox,followActivityUri:activityId,deliveryState:"queued",queue:q};}
async function unfollow(uid:string,local:any,target:string){const remote=await resolve(local,target),existing=await relationship(uid,remote.actorUrl);if(!existing||existing.state==="removed")return{ok:true,idempotent:true,state:"removed",actorUrl:remote.actorUrl};if(!existing.follow_activity_uri)throw Error("Cannot undo follow without the original Follow activity URI");const activityId=await stableActivityId(local.actor_url,remote.actorUrl,"undo"),activity={"@context":CTX,id:activityId,type:"Undo",actor:local.actor_url,object:{id:existing.follow_activity_uri,type:"Follow",actor:local.actor_url,object:remote.actorUrl}};const q=await queue(local,uid,remote.inbox,activity);await upsertRelationship({local_user_id:uid,remote_actor_uri:remote.actorUrl,state:"pending",undo_activity_uri:activityId,remote_inbox_uri:remote.inbox,delivery_state:"queued",updated_at:new Date().toISOString()});return{ok:true,state:"pending",actorUrl:remote.actorUrl,undoActivityUri:activityId,deliveryState:"queued",queue:q};}
async function handle(req:Request){if(!internal(req))return json({error:"Internal federation transport only"},403);const body=await req.json() as any,uid=String(body.user_id||"");if(!uid)return json({error:"user_id required"},400);const local=await actorForUser(uid);if(body.operation==="resolve"){if(!body.target)return json({error:"target required"},400);return json({ok:true,...await resolve(local,body.target)});}if(body.operation==="follow"){if(!body.target)return json({error:"target required"},400);return json(await follow(uid,local,String(body.target)));}if(body.operation==="unfollow"){if(!body.target)return json({error:"target required"},400);return json(await unfollow(uid,local,String(body.target)));}if(body.operation==="deliver"){const target=String(body.target||""),activity=body.activity;if(!target||!activity?.type)return json({error:"target and activity.type required"},400);const remote=await resolve(local,target),activityWithId={"@context":activity["@context"]||CTX,id:activity.id||`${local.actor_url}#activities/${crypto.randomUUID()}`,...activity,actor:activity.actor||local.actor_url};const q=await queue(local,uid,remote.inbox,activityWithId);return json({ok:true,activity:activityWithId,remote:{actorUrl:remote.actorUrl,inbox:remote.inbox},delivery:{status:"queued",queue:q}},202);}if(body.operation==="health")return json({ok:true,service:"federation-transport",activityPub:true,federationOrigin:ORIGIN,version:"3.0",deliveryMode:"queue-first"});return json({error:"Unknown federation transport operation"},400);}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(req.method==="GET"&&new URL(req.url).pathname.endsWith("/health"))return json({ok:true,service:"federation-transport",activityPub:true,federationOrigin:ORIGIN,version:"3.0",deliveryMode:"queue-first"});if(req.method!=="POST")return json({error:"POST required"},405);try{return await handle(req);}catch(e){console.error("federation-transport",e);return json({ok:false,error:e instanceof Error?e.message:"Federation transport failed"},502);}});
