import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || Deno.env.get("SUPABASE_SECRET_KEY") || "";
const ANON = Deno.env.get("SUPABASE_ANON_KEY") || Deno.env.get("SUPABASE_PUBLISHABLE_KEY") || "";
const GATEWAY = `${URL}/functions/v1/gateway-relay`;
const FEED = `${URL}/functions/v1/feed-fast`;
const POST_CREATE = `${URL}/functions/v1/post-create`;
const CORS = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info, x-supabase-api-version","Access-Control-Allow-Methods":"GET,POST,DELETE,OPTIONS"};
const admin = createClient(URL, SERVICE, { auth: { persistSession:false, autoRefreshToken:false } });
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...CORS,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
async function authUser(auth:string|null){if(!auth||!ANON)return null;const r=await fetch(`${URL}/auth/v1/user`,{headers:{apikey:ANON,Authorization:auth}});if(!r.ok)return null;const u=await r.json();return u?.id?u:null;}
async function callFunction(target:string,method:string,body:unknown,auth:string|null,params:Record<string,string>={}){const u=new URL(target);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);const r=await fetch(u,{method,headers:{"Content-Type":"application/json",...(auth?{Authorization:auth}:{})},body:["GET","HEAD"].includes(method)?undefined:JSON.stringify(body??{})});const text=await r.text();return new Response(text,{status:r.status,headers:{...CORS,"Content-Type":r.headers.get("Content-Type")||"application/json; charset=utf-8","Cache-Control":"no-store"}});}
async function gateway(path:string,method:string,body:unknown,params:Record<string,string>,auth:string|null){const r=await fetch(GATEWAY,{method:"POST",headers:{"Content-Type":"application/json",...(auth?{Authorization:auth}:{})},body:JSON.stringify({path,method,body,params})});const text=await r.text();return new Response(text,{status:r.status,headers:{...CORS,"Content-Type":r.headers.get("Content-Type")||"application/json; charset=utf-8","Cache-Control":"no-store"}});}
async function localTimeline(params:Record<string,string>){const limit=Math.min(100,Math.max(1,Number(params.limit||50)));let q=admin.from("posts").select("*,author:profiles!posts_author_id_fkey(*)").is("deleted_at",null).eq("visibility","public").order("created_at",{ascending:false}).limit(limit);if(params.before)q=q.lt("created_at",params.before);const r=await q;if(r.error)return json({error:r.error.message},500);return json(r.data||[]);}
async function notifications(auth:string|null){const user=await authUser(auth);if(!user)return json({error:"Authentication required"},401);const r=await admin.from("notifications").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100);if(r.error)return json({error:r.error.message},500);return json(r.data||[]);}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});try{const auth=req.headers.get("Authorization");const url=new URL(req.url);let envelope:any={};if(!["GET","HEAD"].includes(req.method)){const text=await req.text();if(text){try{envelope=JSON.parse(text)}catch{envelope={}}}}const path=String(envelope.path||url.pathname.replace(/^\/functions\/v1\/testagram-api/,"").replace(/^\/testagram-api/,"")||"/health");const method=String(envelope.method||req.method).toUpperCase();const body=envelope.body??{};const params:Record<string,string>={...Object.fromEntries(url.searchParams.entries()),...(envelope.params||{})};if(path==="/"||path==="/health")return json({ok:true,service:"testagram-api",backend:"supabase",onspaceDependency:false,federation:true,apiVersion:"2"});if(path==="/timeline/home")return callFunction(FEED,"POST",{mode:"home",limit:params.limit||20,before:params.before||undefined},auth,{});if(path==="/timeline/global")return callFunction(FEED,"POST",{mode:"explore",limit:params.limit||20,before:params.before||undefined},auth,{});if(path==="/timeline/local")return localTimeline(params);if(path==="/timeline/federated")return gateway(path,method,body,params,auth);if(path==="/posts"&&method==="POST")return callFunction(POST_CREATE,"POST",body,auth,{});if(path==="/notifications"&&method==="GET")return notifications(auth);if(path==="/notifications"&&method==="DELETE"){const user=await authUser(auth);if(!user)return json({error:"Authentication required"},401);const r=await admin.from("notifications").delete().eq("user_id",user.id);if(r.error)return json({error:r.error.message},500);return json({ok:true});}return gateway(path,method,body,params,auth);}catch(error){console.error("testagram-api failure",error);return json({error:error instanceof Error?error.message:"Testagram API failure"},500);}});