import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { actorKeyMatches, federationJson } from "../_shared/federation-security.ts";
import { processActivityCompat } from "../_shared/activitypub-compat.ts";
const URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SUPABASE_SECRET_KEY')||'';
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'accept,content-type,date,digest,signature,signature-input,content-digest,host,x-testagram-edge-verified,x-testagram-verified-actor,authorization,apikey','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{...CORS,'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
const text=(v:unknown)=>typeof v==='string'?v:'';const uri=(v:unknown)=>typeof v==='string'?v:v&&typeof v==='object'?text((v as any).id):'';
const b64=(x:ArrayBuffer)=>btoa(String.fromCharCode(...new Uint8Array(x)));const ub64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const pem=(s:string)=>ub64(s.replace(/-----BEGIN PUBLIC KEY-----|-----END PUBLIC KEY-----|\s/g,''));
function parts(v:string){const o:any={};for(const p of v.split(/,(?=\w+=)/)){const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=p.slice(i+1).trim().replace(/^"|"$/g,'')}return o;}
async function legacy(req:Request,raw:string,actor:string){const sig=req.headers.get('signature'),digest=req.headers.get('digest'),date=req.headers.get('date');if(!sig||!digest||!date)throw Error('missing HTTP signature headers');const when=Date.parse(date);if(!Number.isFinite(when)||Math.abs(Date.now()-when)>12*60*60*1000)throw Error('stale Date header');const expected=`SHA-256=${b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)))}`;if(digest.toLowerCase()!==expected.toLowerCase())throw Error('digest mismatch');const p=parts(sig);if((p.algorithm||'').toLowerCase()!=='rsa-sha256'||!p.signature||!p.keyId||!p.headers)throw Error('unsupported HTTP signature');if(p.keyId.split('#')[0]!==actor)throw Error('signature key owner mismatch');const a=await federationJson(actor);if(!actorKeyMatches(a,actor))throw Error('remote actor key invalid');const key=await crypto.subtle.importKey('spki',pem(a.publicKey.publicKeyPem),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const u=new URL(req.url),lines:string[]=[];for(const h of p.headers.toLowerCase().split(/\s+/).filter(Boolean)){if(h==='(request-target)')lines.push(`(request-target): ${req.method.toLowerCase()} ${u.pathname}${u.search}`);else if(h==='host')lines.push(`host: ${u.host}`);else{const v=req.headers.get(h);if(v===null)throw Error(`signed header missing: ${h}`);lines.push(`${h}: ${v}`);}}if(!await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,ub64(p.signature),new TextEncoder().encode(lines.join('\n'))))throw Error('HTTP signature invalid');}
async function rfc(req:Request,raw:string,actor:string){const input=req.headers.get('signature-input'),sig=req.headers.get('signature'),digest=req.headers.get('content-digest');if(!input||!sig||!digest)throw Error('missing RFC9421 headers');const m=input.match(/^sig1=(\([^)]*\))(.*)$/);if(!m)throw Error('malformed Signature-Input');const comps=[...m[1].matchAll(/"([^"]+)"/g)].map(x=>x[1]);const params=m[1]+m[2];const created=Number(m[2].match(/;created=(\d+)/)?.[1]||0),keyId=m[2].match(/;keyid="([^"]+)"/)?.[1]||'',alg=m[2].match(/;alg="([^"]+)"/)?.[1]||'';if(alg!=='rsa-v1_5-sha256'||keyId.split('#')[0]!==actor||!created||Math.abs(Date.now()/1000-created)>300||!comps.includes('@method')||!comps.includes('@target-uri')||!comps.includes('content-digest'))throw Error('invalid RFC9421 signature parameters');const dm=digest.match(/^sha-256=:([^:]+):$/i),sm=sig.match(/^sig1=:([^:]+):$/);if(!dm||!sm)throw Error('invalid RFC9421 digest/signature');const expected=b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)));if(dm[1]!==expected)throw Error('Content-Digest mismatch');const a=await federationJson(actor);if(!actorKeyMatches(a,actor))throw Error('remote actor key invalid');const key=await crypto.subtle.importKey('spki',pem(a.publicKey.publicKeyPem),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const base=`"@method": ${req.method}\n"@target-uri": ${new URL(req.url).toString()}\n"content-digest": ${digest}\n"@signature-params": ${params}`;if(!await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,ub64(sm[1]),new TextEncoder().encode(base)))throw Error('RFC9421 signature invalid');}
async function verify(req:Request,raw:string,actor:string){if(req.headers.get('signature-input'))return rfc(req,raw,actor);return legacy(req,raw,actor);}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});if(req.method!=='POST')return json({error:'POST required'},405);try{const ct=req.headers.get('content-type')||'';if(!/(activity\+json|ld\+json|application\/json)/i.test(ct))return json({error:'Unsupported ActivityPub content type'},415);const raw=await req.text();if(!raw||raw.length>2_000_000)return json({error:'Invalid activity body'},400);const activity=JSON.parse(raw);const actor=uri(activity.actor),type=text(activity.type),id=text(activity.id)||`urn:testagram:inbound:${crypto.randomUUID()}`;if(!actor.startsWith('https://')||!type)return json({error:'Activity type and HTTPS actor are required'},400);const edge=req.headers.get('x-testagram-edge-verified')==='true';if(edge){const credential=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim()||(req.headers.get('apikey')||'').trim();if(!SERVICE||credential!==SERVICE||req.headers.get('x-testagram-verified-actor')!==actor)return json({error:'Invalid edge verification'},401);}else await verify(req,raw,actor);
const replay=await db.from('federation_replays').insert({activity_uri:id,actor_uri:actor,signature_key_id:edge?`${actor}#edge-verified`:actor,expires_at:new Date(Date.now()+300000).toISOString()});if(replay.error){if(replay.error.code==='23505')return new Response(null,{status:202,headers:CORS});throw replay.error;}
const received=new Date().toISOString();const p=await db.from('federated_activities').upsert({uri:id,activity_type:type,actor_uri:actor,object_uri:uri(activity.object)||null,target_uri:uri(activity.target)||null,raw_activity:activity,payload:activity,received_at:received,processing_state:'processing',processing_attempts:1},{onConflict:'uri'}).select('id').single();if(p.error)throw p.error;const legacyInbox=await db.from('federation_inbox').upsert({activity_id:id,activity_type:type,actor_url:actor,payload:activity,processing_status:'received',received_at:received},{onConflict:'activity_id'});if(legacyInbox.error)throw legacyInbox.error;
let last='';for(let attempt=1;attempt<=3;attempt++){try{await processActivityCompat(db,activity,actor);const done=new Date().toISOString();await db.from('federated_activities').update({processed_at:done,processing_state:'processed',processing_attempts:attempt,processing_error:null,last_processing_error:null,next_processing_at:null}).eq('uri',id);await db.from('federation_inbox').update({processing_status:'processed',error:null,processed_at:done}).eq('activity_id',id);return new Response(null,{status:202,headers:CORS});}catch(e){last=e instanceof Error?e.message:String(e);await db.from('federated_activities').update({processing_attempts:attempt,processing_error:last,last_processing_error:last}).eq('uri',id);if(attempt<3)await new Promise(r=>setTimeout(r,250*attempt));}}
await db.from('federated_activities').update({processing_state:'retry',processing_error:last,last_processing_error:last,next_processing_at:new Date(Date.now()+30000).toISOString()}).eq('uri',id);return new Response(null,{status:202,headers:CORS});}catch(e){console.error('[federation-inbox]',e);return json({error:e instanceof Error?e.message:'Malformed ActivityPub request'},401);}});
